export const AUDIT_ACTION_LABELS: Record<string, string> = {
  create_case: "Casus aangemaakt",
  start_intake: "Intake gestart",
  complete_wijkteam_intake: "Wijkteam intake voltooid",
  complete_zorgvraag_assessment: "Zorgvraag beoordeeld",
  complete_summary: "Samenvatting voltooid",
  generate_summary: "Samenvatting gegenereerd",
  start_matching: "Matching gestart",
  validate_matching: "Voorstel gevalideerd",
  send_to_provider: "Verstuurd naar aanbieder",
  provider_accept: "Aanbieder geaccepteerd",
  provider_reject: "Aanbieder afgewezen",
  provider_request_info: "Informatie opgevraagd",
  budget_approve: "Budget goedgekeurd",
  budget_reject: "Budget afgewezen",
  budget_request_info: "Budget informatie gevraagd",
  budget_defer: "Budget uitgesteld",
  confirm_placement: "Plaatsing bevestigd",
  activate_placement_monitoring: "Monitoring geactiveerd",
  archive_case: "Casus gearchiveerd",
  rematch: "Hermatching gestart",
  submit_transition_request: "Transitieverzoek ingediend",
  resolve_transition_financial: "Financiële transitie afgerond",
  intake_create_api: "Intake aangemaakt",
  assessment_decision_api: "Beoordelingsbeslissing vastgelegd",
  complexity_confirmed: "Complexiteit bevestigd",
  complexity_overridden: "Complexiteit gewijzigd",
  care_intensity_confirmed: "Zorgintensiteit bevestigd",
  care_intensity_overridden: "Zorgintensiteit gewijzigd",
  STATE_TRANSITION: "Status gewijzigd",
  CREATE: "Aangemaakt",
  UPDATE: "Gewijzigd",
  APPROVE: "Goedgekeurd",
  REJECT: "Afgewezen",
  DELETE: "Verwijderd",
};

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}
