export const CARE_TERMS = {
  workflow: {
    casus: "Aanvraag",
    samenvatting: "Zorgvraag",
    matching: "Matching",
    gemeenteValidatie: "Gemeentelijke validatie",
    aanbiederBeoordeling: "Aanbieder reacties",
    plaatsing: "Plaatsing",
    intake: "Intake",
    plaatsingEnIntake: "Plaatsing & uitstroom",
  },
  roles: {
    aanmelder: "Aanmelder",
    gemeente: "Gemeente",
    zorgaanbieder: "Zorgaanbieder",
    admin: "Admin",
    systeem: "Platform",
  },
  surfaces: {
    regiekamer: "Coördinatie",
    casussen: "Aanvragen",
    matching: "Matching",
    acties: "Acties",
    beoordelingen: "Reacties",
    plaatsingen: "Plaatsingen",
    zorgaanbieders: "Zorgaanbieders",
    gemeenten: "Gemeenten",
    regios: "Regio's",
    documenten: "Documenten",
    audittrail: "Audittrail",
    instellingen: "Instellingen",
  },
} as const;
