# Generated by Django 4.2.23 on 2025-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INTERNAL_REVIEW', 'Internal Review'), ('EXTERNAL_REVIEW', 'External Review'), ('NEGOTIATION', 'Negotiation'), ('SIGNATURE', 'Signature'), ('EXECUTION', 'Execution'), ('RENEWAL_TERMINATION', 'Renewal/Termination')], default='DRAFT', max_length=20),
        ),
    ]
