# Generated by Django 4.2.23 on 2025-08-14 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_contractversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('internal_note', models.TextField(blank=True)),
                ('external_note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='negotiation_attachments/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negotiation_posts', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_threads', to='contracts.contract')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
