# Generated by Django 5.2.5 on 2026-04-04 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_organizationinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='contracts_o_organiz_1dad47_idx',
            old_name='contracts_or_organiz_50e7a0_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitation',
            new_name='contracts_o_email_b87530_idx',
            old_name='contracts_or_email_0fb5b9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='contracts.organization'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='due_diligence_processes', to='contracts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('organization', 'year', 'quarter', 'department')},
        ),
    ]
