# Generated by Django 4.2.23 on 2025-08-14 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_negotiationthread'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrademarkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('class_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILED', 'Filed'), ('IN_REVIEW', 'In Review'), ('REGISTERED', 'Registered'), ('REJECTED', 'Rejected'), ('ABANDONED', 'Abandoned')], default='PENDING', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('documents', models.FileField(blank=True, null=True, upload_to='trademark_documents/')),
                ('renewal_deadline', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trademark_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
