# Generated by Django 5.2.5 on 2026-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_add_org_fk_to_budget_and_due_diligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='case_phase',
            field=models.CharField(choices=[('intake', 'Intake'), ('beoordeling', 'Beoordeling'), ('matching', 'Matching'), ('plaatsing', 'Plaatsing'), ('actief', 'Actief'), ('afgerond', 'Afgerond')], default='intake', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='phase_entered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the case entered the current phase', null=True),
        ),
    ]
