# Generated by Django 5.2.5 on 2026-04-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_add_case_phase_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='matter',
            name='scope',
            field=models.CharField(choices=[('GEMEENTE', 'Gemeente'), ('REGIO', 'Regio')], default='GEMEENTE', help_text='Municipality or Regional scope', max_length=20),
        ),
    ]
