# Generated by Django 5.2.5 on 2026-04-08 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_matter_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCategoryMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Care Category (Main)',
                'verbose_name_plural': 'Care Categories (Main)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DEBT', 'Schulden'), ('VIOLENCE', 'Geweld'), ('ADDICTION', 'Verslaving'), ('MENTAL_HEALTH', 'Psychische problematiek'), ('HOMELESSNESS', 'Huisvesting'), ('SOCIAL_ISOLATION', 'Sociale isolatie'), ('EMPLOYMENT', 'Werkloosheid'), ('LEGAL', 'Juridische problemen'), ('TRAUMA', 'Trauma'), ('OTHER', 'Anderszins')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Risk Factor',
                'verbose_name_plural': 'Risk Factors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='duediligenceprocess',
            options={'ordering': ['-created_at'], 'verbose_name': 'Intake & Beoordeling', 'verbose_name_plural': 'Intakes & Beoordelingen'},
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='assessment_summary',
            field=models.TextField(blank=True, help_text='Hulpvraag samenvatting, urgentie, aandachtspunten', verbose_name='Intake samenvatting'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='client_age_category',
            field=models.CharField(blank=True, choices=[('0_4', '0–4'), ('4_12', '4–12'), ('12_18', '12–18'), ('18_PLUS', '18+')], max_length=10, null=True, verbose_name='Leeftijdscategorie cliënt'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='complexity',
            field=models.CharField(choices=[('SIMPLE', 'Enkelvoudig'), ('MULTIPLE', 'Meervoudig'), ('SEVERE', 'Zwaar')], default='SIMPLE', max_length=20, verbose_name='Complexiteit'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='family_situation',
            field=models.CharField(blank=True, choices=[('HOME_DWELLING', 'Thuiswonend'), ('DIVORCED_PARENTS', 'Gescheiden ouders'), ('FOSTER_CARE', 'Pleegzorg'), ('INSTITUTION', 'Instelling'), ('OTHER', 'Anders')], max_length=20, null=True, verbose_name='Gezinssituatie'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='has_other_support',
            field=models.BooleanField(default=False, verbose_name='Betrokken hulp (ja/nee)'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='other_support_description',
            field=models.TextField(blank=True, verbose_name='Beschrijving betrokken hulp'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='preferred_care_form',
            field=models.CharField(choices=[('OUTPATIENT', 'Ambulant'), ('DAY_TREATMENT', 'Dagbehandeling'), ('RESIDENTIAL', 'Residentieel'), ('CRISIS', 'Crisisopvang')], default='OUTPATIENT', max_length=20, verbose_name='Gewenste zorgvorm'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='school_work_status',
            field=models.CharField(blank=True, max_length=200, verbose_name='School- / werkstatus'),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog'), ('CRISIS', 'Crisis')], default='MEDIUM', max_length=10, verbose_name='Urgentie'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aanvullende opmerkingen'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='lead_attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dd_processes', to=settings.AUTH_USER_MODEL, verbose_name='Casusregisseur'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='start_date',
            field=models.DateField(verbose_name='Intakedatum'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='status',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('ASSESSMENT', 'Beoordeling'), ('MATCHING', 'Matching'), ('DECISION', 'Matchbesluit'), ('COMPLETED', 'Afgerond'), ('ON_HOLD', 'In wacht')], default='INTAKE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='target_company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='target_completion_date',
            field=models.DateField(verbose_name='Doeldatum matchbesluit'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='title',
            field=models.CharField(help_text='Bijv. voornaam + initialiteit', max_length=200, verbose_name='Casusidentificatie'),
        ),
        migrations.AlterField(
            model_name='duediligenceprocess',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='care_category_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes_main', to='contracts.carecategorymain', verbose_name='Hoofdcategorie zorgvraag'),
        ),
        migrations.CreateModel(
            name='CareCategorySubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='contracts.carecategorymain')),
            ],
            options={
                'verbose_name': 'Care Subcategory',
                'verbose_name_plural': 'Care Subcategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='care_category_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intakes_sub', to='contracts.carecategorysubcategory', verbose_name='Subcategorie zorgvraag'),
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_age_0_4', models.BooleanField(default=False, verbose_name='Target: 0–4')),
                ('target_age_4_12', models.BooleanField(default=False, verbose_name='Target: 4–12')),
                ('target_age_12_18', models.BooleanField(default=False, verbose_name='Target: 12–18')),
                ('target_age_18_plus', models.BooleanField(default=False, verbose_name='Target: 18+')),
                ('offers_outpatient', models.BooleanField(default=False, verbose_name='Aanbod: Ambulant')),
                ('offers_day_treatment', models.BooleanField(default=False, verbose_name='Aanbod: Dagbehandeling')),
                ('offers_residential', models.BooleanField(default=False, verbose_name='Aanbod: Residentieel')),
                ('offers_crisis', models.BooleanField(default=False, verbose_name='Aanbod: Crisisopvang')),
                ('handles_simple', models.BooleanField(default=False, verbose_name='Kan: Enkelvoudig')),
                ('handles_multiple', models.BooleanField(default=False, verbose_name='Kan: Meervoudig')),
                ('handles_severe', models.BooleanField(default=False, verbose_name='Kan: Zwaar')),
                ('handles_low_urgency', models.BooleanField(default=False, verbose_name='Kan: Laag')),
                ('handles_medium_urgency', models.BooleanField(default=False, verbose_name='Kan: Middel')),
                ('handles_high_urgency', models.BooleanField(default=False, verbose_name='Kan: Hoog')),
                ('handles_crisis_urgency', models.BooleanField(default=False, verbose_name='Kan: Crisis')),
                ('current_capacity', models.PositiveIntegerField(default=0, verbose_name='Huidige beschikbaarheid (aantal plaatsen)')),
                ('max_capacity', models.PositiveIntegerField(default=0, verbose_name='Maximale capaciteit')),
                ('waiting_list_length', models.PositiveIntegerField(default=0, verbose_name='Wachtlijst lengte')),
                ('average_wait_days', models.PositiveIntegerField(default=0, verbose_name='Gemiddelde wachttijd (dagen)')),
                ('special_facilities', models.TextField(blank=True, verbose_name='Speciale faciliteiten')),
                ('service_area', models.CharField(blank=True, max_length=500, verbose_name='Dienstgebied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(help_text='Link to care provider/aanbieder', on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to='contracts.client')),
                ('target_care_categories', models.ManyToManyField(blank=True, related_name='provider_profiles', to='contracts.carecategorymain', verbose_name='Zorgvraagcategorieën')),
            ],
            options={
                'verbose_name': 'Provider Profile',
                'verbose_name_plural': 'Provider Profiles',
            },
        ),
        migrations.AddField(
            model_name='duediligenceprocess',
            name='risk_factors',
            field=models.ManyToManyField(blank=True, related_name='intakes', to='contracts.riskfactor', verbose_name='Risicofactoren'),
        ),
    ]
