# Generated by Django 5.2.5 on 2026-04-08 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_carecategorymain_riskfactor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trademarkrequest',
            name='care_form',
            field=models.CharField(blank=True, choices=[('OUTPATIENT', 'Ambulant'), ('DAY_TREATMENT', 'Dagbehandeling'), ('RESIDENTIAL', 'Residentieel'), ('CRISIS', 'Crisisopvang')], max_length=20, verbose_name='Zorgvorm'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='decision_notes',
            field=models.TextField(blank=True, verbose_name='Besluitnotities'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='due_diligence_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indications', to='contracts.duediligenceprocess', verbose_name='Casus'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duur (weken, optioneel)'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='proposed_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_indications', to='contracts.client', verbose_name='Voorgestelde aanbieder'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='selected_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_indications', to='contracts.client', verbose_name='Geselecteerde aanbieder'),
        ),
        migrations.AddField(
            model_name='trademarkrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum'),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='filing_basis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='goods_services',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='mark_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='trademarkrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Concept'), ('IN_REVIEW', 'In beoordeling'), ('APPROVED', 'Goedgekeurd'), ('REJECTED', 'Afgewezen'), ('NEEDS_INFO', 'Aanvullende info nodig')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_status', models.CharField(choices=[('DRAFT', 'Concept'), ('UNDER_REVIEW', 'In beoordeling'), ('APPROVED_FOR_MATCHING', 'Goedgekeurd voor matching'), ('NEEDS_INFO', 'Aanvullende info nodig')], default='DRAFT', max_length=32, verbose_name='Beoordeling status')),
                ('risk_signals', models.CharField(blank=True, help_text='Comma-separated risk signal codes', max_length=200, verbose_name="Risico's / Signalen")),
                ('matching_ready', models.BooleanField(default=False, verbose_name='Klaar voor matching')),
                ('reason_not_ready', models.TextField(blank=True, help_text='Toelichting waarom nog niet klaar voor matching', verbose_name='Reden indien niet klaar')),
                ('notes', models.TextField(blank=True, help_text='Vrije notities bij beoordeling', verbose_name='Notities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assessments_performed', to=settings.AUTH_USER_MODEL, verbose_name='Beoordeeld door')),
                ('due_diligence_process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_assessment', to='contracts.duediligenceprocess', verbose_name='Casus')),
            ],
            options={
                'verbose_name': 'Casusbeoordeling',
                'verbose_name_plural': 'Casusbeoordelingen',
                'ordering': ['-created_at'],
            },
        ),
    ]
