# Generated by Django 5.2.5 on 2025-08-18 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_risklog_compliancechecklist_checklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('projected_completion', models.DateField(blank=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_workflows', to='contracts.workflowstep')),
            ],
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='contracts.workflow'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(blank=True, choices=[('NDA', 'Non-Disclosure Agreement'), ('MSA', 'Master Service Agreement'), ('SOW', 'Statement of Work'), ('SLA', 'Service Level Agreement'), ('EMPLOYMENT', 'Employment Agreement'), ('OTHER', 'Other')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workflow',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('INTERNAL_REVIEW', 'Internal Review'), ('EXTERNAL_REVIEW', 'External Review'), ('NEGOTIATION', 'Negotiation'), ('SIGNATURE', 'Signature'), ('EXECUTION', 'Execution')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('default_assignee_role', models.CharField(blank=True, max_length=50)),
                ('estimated_days', models.PositiveIntegerField(default=3)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_steps', to='contracts.workflowtemplate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
    ]
