# Generated by Django 5.2.5 on 2026-04-08 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_trademarkrequest_care_form_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='risklog',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_signals', to=settings.AUTH_USER_MODEL, verbose_name='Verantwoordelijke'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='due_diligence_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='contracts.duediligenceprocess', verbose_name='Casus'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='follow_up',
            field=models.TextField(blank=True, verbose_name='Opvolging'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='signal_type',
            field=models.CharField(choices=[('SAFETY', 'Veiligheid'), ('ESCALATION', 'Escalatie'), ('NO_MATCH', 'Geen match'), ('WAIT_EXCEEDED', 'Wachttijd overschreden'), ('CAPACITY_ISSUE', 'Capaciteit probleem'), ('INTAKE_INCOMPLETE', 'Intake incompleet'), ('DROPOUT_RISK', 'Uitval risico')], default='SAFETY', max_length=30, verbose_name='Type signaal'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In opvolging'), ('RESOLVED', 'Afgerond')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='description',
            field=models.TextField(verbose_name='Omschrijving'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog'), ('CRITICAL', 'Kritisch')], default='MEDIUM', max_length=10, verbose_name='Urgentie'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titel (optioneel)'),
        ),
    ]
