# Generated by Django 5.2.5 on 2026-04-08 21:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_risklog_assigned_to_risklog_due_diligence_process_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='care_type',
            field=models.CharField(choices=[('OUTPATIENT', 'Ambulant'), ('DAY_TREATMENT', 'Dagbehandeling'), ('RESIDENTIAL', 'Residentieel'), ('CRISIS', 'Crisisopvang')], default='OUTPATIENT', max_length=20, verbose_name='Zorgtype'),
        ),
        migrations.AddField(
            model_name='budget',
            name='linked_cases',
            field=models.ManyToManyField(blank=True, related_name='capacity_budgets', to='contracts.duediligenceprocess', verbose_name='Gekoppelde casussen'),
        ),
        migrations.AddField(
            model_name='budget',
            name='linked_placements',
            field=models.ManyToManyField(blank=True, related_name='capacity_budgets', to='contracts.trademarkrequest', verbose_name='Gekoppelde plaatsingen'),
        ),
        migrations.AddField(
            model_name='budget',
            name='linked_providers',
            field=models.ManyToManyField(blank=True, help_text='Optioneel: koppel aanbieders aan dit budget.', related_name='capacity_budgets', to='contracts.client', verbose_name='Gekoppelde aanbieders'),
        ),
        migrations.AddField(
            model_name='budget',
            name='scope_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Gemeente / regio'),
        ),
        migrations.AddField(
            model_name='budget',
            name='scope_type',
            field=models.CharField(choices=[('GEMEENTE', 'Gemeente'), ('REGIO', 'Regio')], default='GEMEENTE', max_length=20, verbose_name='Gemeente / regio type'),
        ),
        migrations.AddField(
            model_name='budget',
            name='target_group',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Doelgroep'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Totaal budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], default='', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('organization', 'year', 'scope_type', 'scope_name', 'target_group', 'care_type')},
        ),
    ]
