# Generated by Django 5.2.5 on 2026-04-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_budget_unique_together_budget_care_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='deadline_type',
        ),
        migrations.RemoveField(
            model_name='deadline',
            name='reminder_days',
        ),
        migrations.AddField(
            model_name='deadline',
            name='due_diligence_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_tasks', to='contracts.duediligenceprocess', verbose_name='Casus'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='task_type',
            field=models.CharField(choices=[('INTAKE_COMPLETE', 'Intake afronden'), ('ASSESSMENT_PERFORM', 'Beoordeling uitvoeren'), ('SELECT_MATCH', 'Match selecteren'), ('CONTACT_PROVIDER', 'Aanbieder contacteren'), ('CONFIRM_PLACEMENT', 'Plaatsing bevestigen'), ('EVALUATE', 'Evaluatie uitvoeren')], default='INTAKE_COMPLETE', max_length=30, verbose_name='Type taak'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Taak'),
        ),
    ]
