# Generated by Django 5.2.5 on 2026-04-08 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_remove_deadline_deadline_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trustaccount',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Wachttijd', 'verbose_name_plural': 'Wachttijden'},
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='client',
        ),
        migrations.RemoveField(
            model_name='trustaccount',
            name='matter',
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='care_type',
            field=models.CharField(choices=[('AMBULANT', 'Ambulant'), ('DAGBESTEDING', 'Dagbesteding'), ('JEUGDHULP', 'Jeugdhulp'), ('GGZ', 'GGZ'), ('WLZ', 'WLZ'), ('OVERIG', 'Overig')], default='AMBULANT', max_length=20, verbose_name='Zorgtype'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Toelichting'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='open_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Beschikbare plekken'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wait_time_entries', to='contracts.client', verbose_name='Aanbieder'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='region',
            field=models.CharField(default='', max_length=120, verbose_name='Regio / gemeente'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='wait_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Gemiddelde wachttijd (dagen)'),
        ),
        migrations.AddField(
            model_name='trustaccount',
            name='waiting_list_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Wachtlijst (aantal)'),
        ),
        migrations.DeleteModel(
            name='TrustTransaction',
        ),
    ]
