# Generated by Django 5.2.5 on 2026-04-08 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_trustaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matter',
            name='case_number',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='court_name',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='opposing_counsel',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='opposing_party',
        ),
        migrations.RemoveField(
            model_name='matter',
            name='statute_of_limitations',
        ),
        migrations.AddField(
            model_name='matter',
            name='care_domains',
            field=models.ManyToManyField(blank=True, related_name='municipality_configurations', to='contracts.carecategorymain'),
        ),
        migrations.AddField(
            model_name='matter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='linked_providers',
            field=models.ManyToManyField(blank=True, related_name='municipality_configurations', to='contracts.client'),
        ),
        migrations.AddField(
            model_name='matter',
            name='max_wait_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='priority_rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matter',
            name='responsible_team',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='matter',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='contracts.client'),
        ),
    ]
