# Generated by Django 5.2.5 on 2026-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_remove_matter_case_number_remove_matter_court_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deadline',
            name='generation_source',
            field=models.CharField(choices=[('MANUAL', 'Handmatig'), ('INTAKE', 'Intake'), ('ASSESSMENT', 'Beoordeling'), ('MATCHING', 'Matching'), ('PLACEMENT', 'Plaatsing')], default='MANUAL', max_length=20),
        ),
    ]
