# Generated by Django 5.2.5 on 2026-04-10 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_care_native_table_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskfactor',
            options={'ordering': ['name'], 'verbose_name': 'Signaalfactor', 'verbose_name_plural': 'Signaalfactoren'},
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_role',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('ASSOCIATE', 'Associate'), ('PARALEGAL', 'Regiemedewerker'), ('LEGAL_ASSISTANT', 'Zorgassistent'), ('ADMIN', 'Administrator'), ('CLIENT', 'Cliënt')], max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='category',
            field=models.CharField(choices=[('LEGAL_FEES', 'Toetsingskosten'), ('CONSULTING', 'Consulting'), ('SOFTWARE', 'Software'), ('TRAVEL', 'Travel'), ('OFFICE', 'Office Supplies'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='risk_signals',
            field=models.CharField(blank=True, help_text='Komma-gescheiden signaalcodes', max_length=200, verbose_name='Signalen'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individuele client'), ('CORPORATION', 'Aanbiederorganisatie'), ('LLC', 'LLC'), ('PARTNERSHIP', 'Samenwerkingsverband'), ('GOVERNMENT', 'Gemeente / overheid'), ('NON_PROFIT', 'Non-profit'), ('OTHER', 'Other')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('NDA', 'Intakeafspraak'), ('MSA', 'Regieafspraak'), ('SOW', 'Uitvoeringsafspraak'), ('EMPLOYMENT', 'Personele inzet'), ('LEASE', 'Capaciteitsafspraak'), ('LICENSE', 'Toegangsafspraak'), ('VENDOR', 'Aanbiedersafspraak'), ('PARTNERSHIP', 'Samenwerkingsafspraak'), ('SETTLEMENT', 'Afstemmingsafspraak'), ('AMENDMENT', 'Wijzigingsafspraak'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='governing_law',
            field=models.CharField(blank=True, help_text='Kader of beleidsgrondslag', max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='Regio of toepassingsgebied', max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lifecycle_stage',
            field=models.CharField(choices=[('DRAFTING', 'Voorbereiding'), ('INTERNAL_REVIEW', 'Interne beoordeling'), ('NEGOTIATION', 'Afstemming'), ('APPROVAL', 'Indicatie'), ('SIGNATURE', 'Bevestiging'), ('EXECUTED', 'Gestart'), ('OBLIGATION_TRACKING', 'Voortgangsbewaking'), ('RENEWAL', 'Herbeoordeling / afronding'), ('ARCHIVED', 'Archived')], default='DRAFTING', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog'), ('CRITICAL', 'Kritiek')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Concept'), ('PENDING', 'Wacht op actie'), ('IN_REVIEW', 'In beoordeling'), ('APPROVED', 'Goedgekeurd'), ('ACTIVE', 'Actief'), ('EXPIRED', 'Verlopen'), ('TERMINATED', 'Beëindigd'), ('COMPLETED', 'Afgerond'), ('CANCELLED', 'Geannuleerd')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='datainventoryrecord',
            name='lawful_basis',
            field=models.CharField(choices=[('CONSENT', 'Toestemming'), ('CONTRACT', 'Uitvoering zorgtraject'), ('LEGAL_OBLIGATION', 'Wettelijke verplichting'), ('VITAL_INTEREST', 'Vitaal belang'), ('PUBLIC_INTEREST', 'Publiek belang'), ('LEGITIMATE_INTEREST', 'Gerechtvaardigd belang')], max_length=25),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Casusdossier'), ('AMENDMENT', 'Wijziging'), ('EXHIBIT', 'Bijlage'), ('CORRESPONDENCE', 'Correspondence'), ('COURT_FILING', 'Formele indiening'), ('PLEADING', 'Onderbouwing'), ('DISCOVERY', 'Discovery'), ('MEMO', 'Memorandum'), ('RESEARCH', 'Onderzoeksnotitie'), ('INVOICE', 'Archived Financial Record'), ('TEMPLATE', 'Template'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Concept'), ('REVIEW', 'In beoordeling'), ('APPROVED', 'Goedgekeurd'), ('FINAL', 'Definitief'), ('ARCHIVED', 'Gearchiveerd')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='duediligencerisk',
            name='category',
            field=models.CharField(choices=[('LEGAL', 'Regelgeving & toetsing'), ('FINANCIAL', 'Budget'), ('OPERATIONAL', 'Operationeel'), ('REPUTATIONAL', 'Reputatie'), ('STRATEGIC', 'Strategisch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='duediligencerisk',
            name='impact',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog')], max_length=10),
        ),
        migrations.AlterField(
            model_name='duediligencerisk',
            name='likelihood',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog')], max_length=10),
        ),
        migrations.AlterField(
            model_name='duediligencerisk',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Middel'), ('HIGH', 'Hoog')], max_length=10),
        ),
        migrations.AlterField(
            model_name='duediligencetask',
            name='category',
            field=models.CharField(choices=[('LEGAL', 'Regelgeving'), ('FINANCIAL', 'Budget'), ('OPERATIONAL', 'Operationeel'), ('TECHNICAL', 'Technisch'), ('REGULATORY', 'Toetsing'), ('COMMERCIAL', 'Samenwerking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='duediligencetask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Open'), ('IN_PROGRESS', 'In uitvoering'), ('COMPLETED', 'Afgerond'), ('BLOCKED', 'Geblokkeerd')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DEADLINE', 'Deadline herinnering'), ('TASK', 'Taaktoewijzing'), ('CONTRACT', 'Casusupdate'), ('APPROVAL', 'Indicatieverzoek'), ('SYSTEM', 'Systeem'), ('BILLING', 'Capaciteitsbudget')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='name',
            field=models.CharField(choices=[('DEBT', 'Schulden'), ('VIOLENCE', 'Geweld'), ('ADDICTION', 'Verslaving'), ('MENTAL_HEALTH', 'Psychische problematiek'), ('HOMELESSNESS', 'Huisvesting'), ('SOCIAL_ISOLATION', 'Sociale isolatie'), ('EMPLOYMENT', 'Werkloosheid'), ('LEGAL', 'Regelgevingsvragen'), ('TRAUMA', 'Trauma'), ('OTHER', 'Anderszins')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='signaturerequest',
            name='signer_role',
            field=models.CharField(blank=True, help_text='Bijv. Teamleider, Regiecoordinator', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('PARTNER', 'Partner'), ('SENIOR_ASSOCIATE', 'Senior Associate'), ('ASSOCIATE', 'Associate'), ('PARALEGAL', 'Regiemedewerker'), ('LEGAL_ASSISTANT', 'Zorgassistent'), ('ADMIN', 'Administrator'), ('CLIENT', 'Cliënt')], default='ASSOCIATE', max_length=20),
        ),
        migrations.CreateModel(
            name='MunicipalityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=150, verbose_name='Gemeente')),
                ('municipality_code', models.CharField(blank=True, max_length=50, verbose_name='Gemeentecode')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actief'), ('INACTIVE', 'Inactief'), ('DRAFT', 'Concept')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('max_wait_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximale wachttijd (dagen)')),
                ('priority_rules', models.TextField(blank=True, verbose_name='Prioriteringsregels')),
                ('notes', models.TextField(blank=True, verbose_name='Notities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_domains', models.ManyToManyField(blank=True, related_name='municipality_configs', to='contracts.carecategorymain', verbose_name='Zorgdomeinen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_municipality_configs', to=settings.AUTH_USER_MODEL)),
                ('linked_providers', models.ManyToManyField(blank=True, related_name='municipality_configs', to='contracts.client', verbose_name='Gekoppelde aanbieders')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipality_configs', to='contracts.organization')),
                ('responsible_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipality_configs', to=settings.AUTH_USER_MODEL, verbose_name='Verantwoordelijke')),
            ],
            options={
                'verbose_name': 'Gemeente Configuratie',
                'verbose_name_plural': 'Gemeente Configuraties',
                'ordering': ['municipality_name'],
                'unique_together': {('organization', 'municipality_code')},
            },
        ),
        migrations.CreateModel(
            name='RegionalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=150, verbose_name='Regio')),
                ('region_code', models.CharField(blank=True, max_length=50, verbose_name='Regiode')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actief'), ('INACTIVE', 'Inactief'), ('DRAFT', 'Concept')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('max_wait_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximale wachttijd (dagen)')),
                ('priority_rules', models.TextField(blank=True, verbose_name='Prioriteringsregels')),
                ('notes', models.TextField(blank=True, verbose_name='Notities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_domains', models.ManyToManyField(blank=True, related_name='regional_configs', to='contracts.carecategorymain', verbose_name='Zorgdomeinen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_regional_configs', to=settings.AUTH_USER_MODEL)),
                ('linked_providers', models.ManyToManyField(blank=True, related_name='regional_configs', to='contracts.client', verbose_name='Gekoppelde aanbieders')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regional_configs', to='contracts.organization')),
                ('responsible_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regional_configs', to=settings.AUTH_USER_MODEL, verbose_name='Verantwoordelijke')),
                ('served_municipalities', models.ManyToManyField(blank=True, related_name='regions', to='contracts.municipalityconfiguration', verbose_name='Bediende gemeenten')),
            ],
            options={
                'verbose_name': 'Regio Configuratie',
                'verbose_name_plural': 'Regio Configuraties',
                'ordering': ['region_name'],
                'unique_together': {('organization', 'region_code')},
            },
        ),
    ]
