# Generated by Django 5.2.5 on 2026-04-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_matter_care_field_renames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='matter',
            name='intake_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matter',
            name='responsible_care_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_configurations', to=settings.AUTH_USER_MODEL),
        ),
    ]
