# Generated by Django 5.2.5 on 2026-04-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0025_rename_models_to_care_native'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE contracts_client RENAME COLUMN originating_attorney_id TO intake_coordinator_id',
                    reverse_sql='ALTER TABLE contracts_client RENAME COLUMN intake_coordinator_id TO originating_attorney_id',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE contracts_client RENAME COLUMN responsible_attorney_id TO responsible_coordinator_id',
                    reverse_sql='ALTER TABLE contracts_client RENAME COLUMN responsible_coordinator_id TO responsible_attorney_id',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE contracts_municipalityconfiguration RENAME COLUMN responsible_attorney_id TO responsible_coordinator_id',
                    reverse_sql='ALTER TABLE contracts_municipalityconfiguration RENAME COLUMN responsible_coordinator_id TO responsible_attorney_id',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE contracts_regionalconfiguration RENAME COLUMN responsible_attorney_id TO responsible_coordinator_id',
                    reverse_sql='ALTER TABLE contracts_regionalconfiguration RENAME COLUMN responsible_coordinator_id TO responsible_attorney_id',
                ),
                migrations.RunSQL(
                    sql='ALTER TABLE contracts_duediligenceprocess RENAME COLUMN lead_attorney_id TO case_coordinator_id',
                    reverse_sql='ALTER TABLE contracts_duediligenceprocess RENAME COLUMN case_coordinator_id TO lead_attorney_id',
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='client',
                    old_name='originating_attorney',
                    new_name='intake_coordinator',
                ),
                migrations.RenameField(
                    model_name='client',
                    old_name='responsible_attorney',
                    new_name='responsible_coordinator',
                ),
                migrations.RenameField(
                    model_name='municipalityconfiguration',
                    old_name='responsible_attorney',
                    new_name='responsible_coordinator',
                ),
                migrations.RenameField(
                    model_name='regionalconfiguration',
                    old_name='responsible_attorney',
                    new_name='responsible_coordinator',
                ),
                migrations.RenameField(
                    model_name='caseintakeprocess',
                    old_name='lead_attorney',
                    new_name='case_coordinator',
                ),
            ],
        ),
        migrations.RunSQL(
            sql='ALTER TABLE contracts_legaltask RENAME TO contracts_caretask',
            reverse_sql='ALTER TABLE contracts_caretask RENAME TO contracts_legaltask',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE contracts_duediligenceprocess RENAME TO contracts_caseintakeprocess',
            reverse_sql='ALTER TABLE contracts_caseintakeprocess RENAME TO contracts_duediligenceprocess',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE contracts_duediligencetask RENAME TO contracts_intaketask',
            reverse_sql='ALTER TABLE contracts_intaketask RENAME TO contracts_duediligencetask',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE contracts_trademarkrequest RENAME TO contracts_placementrequest',
            reverse_sql='ALTER TABLE contracts_placementrequest RENAME TO contracts_trademarkrequest',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE contracts_duediligenceprocess_risk_factors RENAME TO contracts_caseintakeprocess_risk_factors',
            reverse_sql='ALTER TABLE contracts_caseintakeprocess_risk_factors RENAME TO contracts_duediligenceprocess_risk_factors',
        ),
    ]
