# Generated by Django 5.2.5 on 2026-04-15 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_casedecisionlog_event_type_expansion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionQualityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_recommendation', models.JSONField(blank=True, help_text='Snapshot of system recommendation from decision log', null=True)),
                ('actual_decision', models.JSONField(blank=True, help_text='Snapshot of actual user action/system decision taken', null=True)),
                ('outcome', models.TextField(blank=True, help_text='What actually happened (placement result, provider response, etc.)')),
                ('decision_quality', models.CharField(choices=[('SYSTEM_CORRECT', 'System recommendation was correct'), ('USER_CORRECT', 'User override was correct'), ('BOTH_ACCEPTABLE', 'Both paths acceptable'), ('BOTH_SUBOPTIMAL', 'Both paths had issues')], default='BOTH_ACCEPTABLE', help_text='Quality assessment of system vs user decision', max_length=20)),
                ('override_present', models.BooleanField(default=False, help_text='Was there a user override of system recommendation?')),
                ('override_type', models.CharField(blank=True, choices=[('provider_selection', 'Provider selection override'), ('action_override', 'Action override (resend/rematch/wait)')], help_text='Type of override if override_present is True', max_length=30)),
                ('primary_reason', models.CharField(choices=[('missing_data', 'Missing or incomplete data'), ('provider_mismatch', 'Provider fit mismatch'), ('capacity_issue', 'Capacity or availability issue'), ('sla_timing', 'SLA timing concern'), ('explanation_unclear', 'System explanation unclear'), ('external_constraint', 'External constraint or policy'), ('other', 'Other reason')], default='other', help_text='Primary reason for the quality assessment', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Additional context or observations from the review')),
                ('review_timestamp', models.DateTimeField(help_text='When the review was performed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
            ],
            options={
                'verbose_name': 'Decision Quality Review',
                'verbose_name_plural': 'Decision Quality Reviews',
                'db_table': 'contracts_decisionqualityreview',
                'ordering': ['-review_timestamp', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='decided_by',
        ),
        migrations.RemoveField(
            model_name='approvalrequest',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='approvalrule',
            name='specific_approver',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='checklistitem',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='clausetemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clausetemplate',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='clausetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='compliancechecklist',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='compliancechecklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conflictcheck',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='conflictcheck',
            name='client',
        ),
        migrations.RemoveField(
            model_name='conflictcheck',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='conflictcheck',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='Counterparty',
        ),
        migrations.RemoveField(
            model_name='datainventoryrecord',
            name='client',
        ),
        migrations.RemoveField(
            model_name='datainventoryrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dsarrequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='dsarrequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='dsarrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ethicalwall',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ethicalwall',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ethicalwall',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='ethicalwall',
            name='restricted_users',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='legalhold',
            name='client',
        ),
        migrations.RemoveField(
            model_name='legalhold',
            name='custodians',
        ),
        migrations.RemoveField(
            model_name='legalhold',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='legalhold',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='negotiationthread',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='negotiationthread',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='retentionpolicy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='signaturerequest',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='signaturerequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='signaturerequest',
            name='document',
        ),
        migrations.RemoveField(
            model_name='subprocessor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transferrecord',
            name='subprocessor',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='matter',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='timeentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transferrecord',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='transferrecord',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='caresignal',
            options={'verbose_name': 'Signaal', 'verbose_name_plural': 'Signalen'},
        ),
        migrations.AlterModelOptions(
            name='placementrequest',
            options={'verbose_name': 'Placement Request', 'verbose_name_plural': 'Placement Requests'},
        ),
        migrations.RenameIndex(
            model_name='casedecisionlog',
            new_name='contracts_c_case_id_a113a1_idx',
            old_name='contracts_c_case_id_f8c805_idx',
        ),
        migrations.RenameIndex(
            model_name='casedecisionlog',
            new_name='contracts_c_event_t_cb78c5_idx',
            old_name='contracts_c_event_t_5ef067_idx',
        ),
        migrations.RenameIndex(
            model_name='systempolicyconfig',
            new_name='contracts_s_key_ff6ab8_idx',
            old_name='contracts_s_key_6a5d57_idx',
        ),
        migrations.AlterField(
            model_name='carecase',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR (€)'), ('OTHER', 'Other')], default='EUR', max_length=5),
        ),
        migrations.AlterField(
            model_name='caserisksignal',
            name='category',
            field=models.CharField(choices=[('GOVERNANCE', 'Regelgeving & toetsing'), ('FINANCIAL', 'Budget'), ('OPERATIONAL', 'Operationeel'), ('REPUTATIONAL', 'Reputatie'), ('STRATEGIC', 'Strategisch')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONTRACT', 'Casusdossier'), ('AMENDMENT', 'Wijziging'), ('EXHIBIT', 'Bijlage'), ('CORRESPONDENCE', 'Correspondence'), ('MEMO', 'Memorandum'), ('RESEARCH', 'Onderzoeksnotitie'), ('TEMPLATE', 'Template'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='intaketask',
            name='category',
            field=models.CharField(choices=[('GOVERNANCE', 'Regelgeving'), ('FINANCIAL', 'Budget'), ('OPERATIONAL', 'Operationeel'), ('TECHNICAL', 'Technisch'), ('REGULATORY', 'Toetsing'), ('COMMERCIAL', 'Samenwerking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='name',
            field=models.CharField(choices=[('DEBT', 'Schulden'), ('VIOLENCE', 'Geweld'), ('ADDICTION', 'Verslaving'), ('MENTAL_HEALTH', 'Psychische problematiek'), ('HOMELESSNESS', 'Huisvesting'), ('SOCIAL_ISOLATION', 'Sociale isolatie'), ('EMPLOYMENT', 'Werkloosheid'), ('GOVERNANCE', 'Regelgevingsvragen'), ('TRAUMA', 'Trauma'), ('OTHER', 'Anderszins')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='category',
            field=models.CharField(choices=[('CONTRACT_REVIEW', 'Zorgovereenkomst review'), ('DUE_DILIGENCE', 'Intake & Beoordeling'), ('TRADEMARK', 'Plaatsingscoordinatie'), ('COMPLIANCE', 'Compliance'), ('GENERAL', 'Algemeen')], default='GENERAL', max_length=30),
        ),
        migrations.AlterModelTable(
            name='caretask',
            table='contracts_caretask',
        ),
        migrations.AlterModelTable(
            name='caseintakeprocess',
            table='contracts_caseintakeprocess',
        ),
        migrations.AlterModelTable(
            name='caserisksignal',
            table='contracts_caserisksignal',
        ),
        migrations.AlterModelTable(
            name='intaketask',
            table='contracts_intaketask',
        ),
        migrations.AlterModelTable(
            name='placementrequest',
            table='contracts_placementrequest',
        ),
        migrations.AddField(
            model_name='decisionqualityreview',
            name='case',
            field=models.ForeignKey(help_text='Case being reviewed', on_delete=django.db.models.deletion.PROTECT, related_name='quality_reviews', to='contracts.caseintakeprocess'),
        ),
        migrations.AddField(
            model_name='decisionqualityreview',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='Placement context (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_reviews', to='contracts.placementrequest'),
        ),
        migrations.AddField(
            model_name='decisionqualityreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Person who performed the review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_quality_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ApprovalRequest',
        ),
        migrations.DeleteModel(
            name='ApprovalRule',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='ClauseCategory',
        ),
        migrations.DeleteModel(
            name='ClauseTemplate',
        ),
        migrations.DeleteModel(
            name='ComplianceChecklist',
        ),
        migrations.DeleteModel(
            name='ConflictCheck',
        ),
        migrations.DeleteModel(
            name='DataInventoryRecord',
        ),
        migrations.DeleteModel(
            name='DSARRequest',
        ),
        migrations.DeleteModel(
            name='EthicalWall',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='LegalHold',
        ),
        migrations.DeleteModel(
            name='NegotiationThread',
        ),
        migrations.DeleteModel(
            name='RetentionPolicy',
        ),
        migrations.DeleteModel(
            name='SignatureRequest',
        ),
        migrations.DeleteModel(
            name='Subprocessor',
        ),
        migrations.DeleteModel(
            name='TimeEntry',
        ),
        migrations.DeleteModel(
            name='TransferRecord',
        ),
        migrations.AddIndex(
            model_name='decisionqualityreview',
            index=models.Index(fields=['case', 'review_timestamp'], name='contracts_d_case_id_98ccdd_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionqualityreview',
            index=models.Index(fields=['decision_quality', 'review_timestamp'], name='contracts_d_decisio_278232_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionqualityreview',
            index=models.Index(fields=['override_present', 'review_timestamp'], name='contracts_d_overrid_eee823_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionqualityreview',
            index=models.Index(fields=['primary_reason', 'review_timestamp'], name='contracts_d_primary_853eba_idx'),
        ),
    ]
