# Generated by Django 5.2.5 on 2026-04-18 21:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0041_decision_quality_weekly_review_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AanbiederVestiging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vestiging_code', models.CharField(blank=True, db_index=True, help_text='Externe vestigingscode', max_length=50)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_aanbiedervestiging',
                'ordering': ['zorgaanbieder__name', 'city'],
            },
        ),
        migrations.CreateModel(
            name='CapaciteitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_slots', models.PositiveIntegerField(default=0)),
                ('waiting_list_size', models.PositiveIntegerField(default=0)),
                ('avg_wait_days', models.PositiveIntegerField(default=0)),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'provider_capaciteitrecord',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractRelatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIEF', 'Actief'), ('VERLOPEN', 'Verlopen'), ('OPGESCHORT', 'Opgeschort'), ('CONCEPT', 'Concept')], default='ACTIEF', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_contractrelatie',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProviderImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_ref', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('source_system', models.CharField(help_text='Identifier van het bronsysteem (bijv. "agbregister_v2")', max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=50)),
                ('triggered_by', models.CharField(blank=True, help_text='Gebruiker of scheduler die de import gestart heeft', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'In wachtrij'), ('RUNNING', 'Bezig'), ('COMPLETED', 'Voltooid'), ('PARTIAL', 'Deels voltooid'), ('FAILED', 'Mislukt')], default='PENDING', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('processed_records', models.PositiveIntegerField(default=0)),
                ('created_records', models.PositiveIntegerField(default=0)),
                ('updated_records', models.PositiveIntegerField(default=0)),
                ('skipped_records', models.PositiveIntegerField(default=0)),
                ('conflicted_records', models.PositiveIntegerField(default=0)),
                ('quarantined_records', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_importbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, help_text='Primaire sleutel in het bronsysteem', max_length=200)),
                ('source_agb_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('source_kvk', models.CharField(blank=True, max_length=20)),
                ('raw_payload', models.JSONField(help_text='Onbewerkte data van het bronsysteem')),
                ('payload_fingerprint', models.CharField(db_index=True, max_length=64)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Wacht op validatie'), ('VALID', 'Geldig'), ('INVALID', 'Ongeldig'), ('QUARANTINED', 'In quarantaine'), ('PROMOTED', 'Gepromoveerd naar canoniek'), ('CONFLICTED', 'Conflict gedetecteerd')], default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0–1.0; lager = minder betrouwbaar')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_stagingrecord',
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('source_value', models.TextField()),
                ('canonical_value', models.TextField()),
                ('resolution_status', models.CharField(choices=[('UNRESOLVED', 'Niet opgelost'), ('ACCEPTED_SOURCE', 'Bronwaarde geaccepteerd'), ('ACCEPTED_CANONICAL', 'Canonieke waarde behouden'), ('MANUAL', 'Handmatig opgelost')], default='UNRESOLVED', max_length=25)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_syncconflict',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Aangemaakt'), ('UPDATED', 'Bijgewerkt'), ('SKIPPED', 'Overgeslagen (geen wijziging)'), ('CONFLICTED', 'Conflict — wacht op resolutie'), ('QUARANTINED', 'In quarantaine geplaatst')], max_length=20)),
                ('field_diffs', models.JSONField(blank=True, default=dict, help_text='{"field": {"from": old, "to": new}}')),
                ('message', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_synclog',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Zorgaanbieder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('agb_code', models.CharField(blank=True, db_index=True, help_text='AGB-code als extern primair sleutel', max_length=20)),
                ('kvk_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('provider_type', models.CharField(choices=[('RESIDENTIEEL', 'Residentiële zorg'), ('AMBULANT', 'Ambulante begeleiding'), ('DAGBEHANDELING', 'Dagbehandeling'), ('THUISBEGELEIDING', 'Thuisbegeleiding'), ('CRISISOPVANG', 'Crisisopvang'), ('OVERIG', 'Overig')], default='OVERIG', max_length=30)),
                ('trust_level', models.CharField(choices=[('VERIFIED', 'Geverifieerd'), ('PROVISIONAL', 'Voorlopig'), ('UNVERIFIED', 'Niet geverifieerd'), ('SUSPENDED', 'Opgeschort')], default='PROVISIONAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('last_source_system', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_zorgaanbieder',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zorgprofiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biedt_ambulant', models.BooleanField(default=False)),
                ('biedt_dagbehandeling', models.BooleanField(default=False)),
                ('biedt_residentieel', models.BooleanField(default=False)),
                ('biedt_crisis', models.BooleanField(default=False)),
                ('biedt_thuisbegeleiding', models.BooleanField(default=False)),
                ('leeftijd_0_4', models.BooleanField(default=False)),
                ('leeftijd_4_12', models.BooleanField(default=False)),
                ('leeftijd_12_18', models.BooleanField(default=False)),
                ('leeftijd_18_plus', models.BooleanField(default=False)),
                ('complexiteit_enkelvoudig', models.BooleanField(default=False)),
                ('complexiteit_meervoudig', models.BooleanField(default=False)),
                ('complexiteit_zwaar', models.BooleanField(default=False)),
                ('urgentie_laag', models.BooleanField(default=False)),
                ('urgentie_middel', models.BooleanField(default=False)),
                ('urgentie_hoog', models.BooleanField(default=False)),
                ('urgentie_crisis', models.BooleanField(default=False)),
                ('regio_codes', models.CharField(blank=True, help_text='Kommagescheiden canonieke regiocodes', max_length=1000)),
                ('specialisaties', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_zorgprofiel',
            },
        ),
        migrations.RenameIndex(
            model_name='decisionqualityweeklyreviewmark',
            new_name='contracts_d_year_126186_idx',
            old_name='dq_week_mark_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionqualityweeklyreviewmark',
            new_name='contracts_d_case_id_2e3d83_idx',
            old_name='dq_case_week_idx',
        ),
        migrations.AlterField(
            model_name='decisionqualityweeklyreviewmark',
            name='week',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='vestiging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capaciteit_records', to='contracts.aanbiedervestiging'),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_contracten', to='contracts.organization'),
        ),
        migrations.AddIndex(
            model_name='providerimportbatch',
            index=models.Index(fields=['source_system', '-created_at'], name='provider_im_source__f6898a_idx'),
        ),
        migrations.AddIndex(
            model_name='providerimportbatch',
            index=models.Index(fields=['status'], name='provider_im_status_632ef1_idx'),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_relaties', to='contracts.providerimportbatch'),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capaciteit_records', to='contracts.providerimportbatch'),
        ),
        migrations.AddField(
            model_name='providerstagingrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_records', to='contracts.providerimportbatch'),
        ),
        migrations.AddField(
            model_name='providersyncconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providersyncconflict',
            name='staging_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='contracts.providerstagingrecord'),
        ),
        migrations.AddField(
            model_name='providersynclog',
            name='staging_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='contracts.providerstagingrecord'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='last_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_providers', to='contracts.providerimportbatch'),
        ),
        migrations.AddField(
            model_name='providersynclog',
            name='canonical_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='providersyncconflict',
            name='canonical_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='providerstagingrecord',
            name='canonical_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_records', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='zorgaanbieder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_relaties', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='zorgaanbieder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestigingen', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='zorgaanbieder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zorgprofiel', to='contracts.zorgaanbieder'),
        ),
        migrations.AddIndex(
            model_name='capaciteitrecord',
            index=models.Index(fields=['vestiging', '-recorded_at'], name='provider_ca_vestigi_c75ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='capaciteitrecord',
            index=models.Index(fields=['import_batch'], name='provider_ca_import__228521_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgaanbieder',
            index=models.Index(fields=['agb_code'], name='provider_zo_agb_cod_9bc1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgaanbieder',
            index=models.Index(fields=['kvk_number'], name='provider_zo_kvk_num_f053c2_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgaanbieder',
            index=models.Index(fields=['trust_level', 'is_active'], name='provider_zo_trust_l_37200e_idx'),
        ),
        migrations.AddIndex(
            model_name='providersynclog',
            index=models.Index(fields=['canonical_provider', '-logged_at'], name='provider_sy_canonic_221059_idx'),
        ),
        migrations.AddIndex(
            model_name='providersynclog',
            index=models.Index(fields=['action'], name='provider_sy_action_41b18d_idx'),
        ),
        migrations.AddIndex(
            model_name='providersyncconflict',
            index=models.Index(fields=['resolution_status'], name='provider_sy_resolut_949350_idx'),
        ),
        migrations.AddIndex(
            model_name='providersyncconflict',
            index=models.Index(fields=['canonical_provider', 'field_name'], name='provider_sy_canonic_df8b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstagingrecord',
            index=models.Index(fields=['batch', 'source_id'], name='provider_st_batch_i_81312c_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstagingrecord',
            index=models.Index(fields=['source_agb_code'], name='provider_st_source__37d4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstagingrecord',
            index=models.Index(fields=['validation_status'], name='provider_st_validat_d7db84_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstagingrecord',
            index=models.Index(fields=['payload_fingerprint'], name='provider_st_payload_beaf48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractrelatie',
            unique_together={('zorgaanbieder', 'organization', 'contract_type')},
        ),
        migrations.AlterUniqueTogether(
            name='aanbiedervestiging',
            unique_together={('zorgaanbieder', 'vestiging_code')},
        ),
    ]
