# Generated by Django 5.2.5 on 2026-04-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_provider_pipeline_canonical'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BronMappingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('issue_type', models.CharField(choices=[('UNKNOWN_VALUE', 'Onbekende bronwaarde'), ('AMBIGUOUS_MAPPING', 'Ambigue mapping'), ('MISSING_FIELD', 'Verplicht veld ontbreekt'), ('TYPE_MISMATCH', 'Type mismatch'), ('FORMAT_ERROR', 'Formaat fout'), ('CUSTOM', 'Overig')], max_length=30)),
                ('veldnaam', models.CharField(blank=True, help_text='Naam van het bronveld dat het issue veroorzaakte', max_length=100)),
                ('bronwaarde', models.TextField(blank=True)),
                ('voorgestelde_mapping', models.TextField(blank=True, help_text='Aanbevolen mapping-aanpassing (handmatig ingevuld of door systeem)')),
                ('opgelost', models.BooleanField(default=False)),
                ('opgelost_op', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_bronmappingissue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactpersoonAanbieder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('functie', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefoon', models.CharField(blank=True, max_length=30)),
                ('is_primair_match_contact', models.BooleanField(default=False)),
                ('is_primair_contract_contact', models.BooleanField(default=False)),
                ('is_primair_intake_contact', models.BooleanField(default=False)),
                ('actief', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider_contactpersoon',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='MatchResultaat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casus_id_extern', models.CharField(blank=True, help_text='Casusidentificatie wanneer geen FK beschikbaar', max_length=100)),
                ('totaalscore', models.FloatField(default=0.0, help_text='Gewogen totaalscore 0.0–1.0')),
                ('score_inhoudelijke_fit', models.FloatField(default=0.0)),
                ('score_capaciteit', models.FloatField(default=0.0)),
                ('score_contract_regio', models.FloatField(default=0.0)),
                ('score_complexiteit', models.FloatField(default=0.0)),
                ('score_performance', models.FloatField(default=0.0)),
                ('confidence_label', models.CharField(choices=[('HOOG', 'Hoge zekerheid'), ('MIDDEL', 'Gemiddelde zekerheid'), ('LAAG', 'Lage zekerheid'), ('ONZEKER', 'Onzeker — data onvolledig')], default='ONZEKER', max_length=10)),
                ('fit_samenvatting', models.TextField(blank=True, help_text='Mensleesbare samenvatting van de match-redenering')),
                ('trade_offs', models.JSONField(blank=True, default=list, help_text='Lijst van trade-offs: [{"factor": "...", "toelichting": "..."}]')),
                ('verificatie_advies', models.TextField(blank=True, help_text='Aanbeveling voor verificatie-stap voor een coördinator')),
                ('uitgesloten', models.BooleanField(default=False)),
                ('uitsluitreden', models.CharField(blank=True, max_length=200)),
                ('ranking', models.PositiveSmallIntegerField(blank=True, help_text='Rangorde binnen de kandidatenlijst voor deze casus', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_matchresultaat',
                'ordering': ['ranking', '-totaalscore'],
            },
        ),
        migrations.CreateModel(
            name='PrestatieProfiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aantal_matches', models.PositiveIntegerField(default=0)),
                ('aantal_plaatsingen', models.PositiveIntegerField(default=0)),
                ('aantal_afwijzingen', models.PositiveIntegerField(default=0)),
                ('succesratio_match_naar_plaatsing', models.FloatField(blank=True, help_text='Ratio matches die leiden tot plaatsing (0.0–1.0)', null=True)),
                ('gemiddelde_reactietijd_uren', models.FloatField(blank=True, help_text='Gemiddelde reactietijd van aanbieder na match-verzoek', null=True)),
                ('gemiddelde_doorlooptijd_dagen', models.FloatField(blank=True, help_text='Gemiddelde doorlooptijd van plaatsing (eerste contact tot start)', null=True)),
                ('intake_no_show_ratio', models.FloatField(blank=True, help_text='Fractie intakes waarbij cliënt niet verschijnt', null=True)),
                ('plaatsing_voortijdig_beeindigd_ratio', models.FloatField(blank=True, help_text='Fractie plaatsingen voortijdig beëindigd', null=True)),
                ('kwalitatieve_opmerking', models.TextField(blank=True)),
                ('laatst_berekend_op', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prestatieprofiel',
                'verbose_name_plural': 'Prestatieprofielen',
                'db_table': 'provider_prestatieprofilerel',
            },
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='agb_code_vestiging',
            field=models.CharField(blank=True, db_index=True, help_text='AGB-code specifiek voor deze vestiging', max_length=20),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='bron_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='bron_laatst_gesynchroniseerd_op',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='bron_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='email_vestiging',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='gemeente',
            field=models.CharField(blank=True, help_text='Gemeente (officieel)', max_length=100),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='huisnummer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='provincie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='regio_jeugd',
            field=models.CharField(blank=True, help_text='Jeugdzorg regio-indeling', max_length=100),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='straat',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aanbiedervestiging',
            name='telefoon_vestiging',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='beschikbaar_vanaf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='beschikbare_capaciteit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='betrouwbaarheid_score',
            field=models.FloatField(blank=True, help_text='0.0–1.0; betrouwbaarheid van de capaciteitsopgave', null=True),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='capaciteit_type',
            field=models.CharField(blank=True, help_text='totaal / residentieel / ambulant / dagbehandeling', max_length=50),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='direct_pleegbaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='gemiddelde_wachttijd_dagen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='laatst_bijgewerkt_door',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='laatst_bijgewerkt_op',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='toelichting_capaciteit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='totale_capaciteit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='wachtlijst_aantal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='capaciteitrecord',
            name='zorgprofiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capaciteit_records', to='contracts.zorgprofiel'),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='actief_contract',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='gemeente',
            field=models.CharField(blank=True, help_text='Gemeente als tekst (naast Organization FK)', max_length=200),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='opmerkingen_contract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='regio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='voorkeursaanbieder',
            field=models.BooleanField(default=False, help_text='Aanbieder is voorkeursaanbieder voor deze gemeente/regio'),
        ),
        migrations.AddField(
            model_name='contractrelatie',
            name='zorgvormen_contract',
            field=models.JSONField(blank=True, default=list, help_text='Gecontracteerde zorgvormen'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='bron_id',
            field=models.CharField(blank=True, help_text='Primaire sleutel in het bronsysteem', max_length=200),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='bron_laatst_gesynchroniseerd_op',
            field=models.DateTimeField(blank=True, help_text='Tijdstip van de laatste synchronisatie vanuit bron', null=True),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='bron_type',
            field=models.CharField(blank=True, choices=[('manual', 'Handmatig ingevoerd'), ('seeded', 'Seed data'), ('csv_import', 'CSV import'), ('api', 'API synchronisatie')], default='manual', help_text='Herkomst van de data', max_length=20),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='handelsnaam',
            field=models.CharField(blank=True, help_text='Handelsnaam zoals geregistreerd bij KVK', max_length=300),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='is_handmatig_overschreven',
            field=models.BooleanField(default=False, help_text='Veld(en) handmatig overschreven — beschermd tegen automatische sync'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='is_handmatig_verrijkt',
            field=models.BooleanField(default=False, help_text='Intern verrijkt door een medewerker (niet overschrijfbaar door import)'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='landelijk_dekkend',
            field=models.BooleanField(default=False, help_text='Aanbieder is nationaal actief'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='logo',
            field=models.CharField(blank=True, help_text='URL of pad naar logo-afbeelding', max_length=500),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='normalisatie_status',
            field=models.CharField(choices=[('PENDING', 'Wacht op normalisatie'), ('NORMALIZED', 'Genormaliseerd'), ('PARTIAL', 'Gedeeltelijk genormaliseerd'), ('FAILED', 'Normalisatie mislukt')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='omschrijving_kort',
            field=models.TextField(blank=True, help_text='Korte beschrijving voor matching context'),
        ),
        migrations.AddField(
            model_name='zorgaanbieder',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Wacht op review'), ('APPROVED', 'Goedgekeurd'), ('FLAGGED', 'Gemarkeerd voor controle'), ('REJECTED', 'Afgewezen')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='aanbieder_vestiging',
            field=models.ForeignKey(blank=True, help_text='Vestiging waaraan dit profiel gekoppeld is', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zorgprofielen', to='contracts.aanbiedervestiging'),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='actief',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='autisme_geschikt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='contra_indicaties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='crisis_opvang_mogelijk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='doelgroep_leeftijd_tot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='doelgroep_leeftijd_van',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='geslacht_beperking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='ggz_comorbiditeit_mogelijk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='intensiteit',
            field=models.CharField(blank=True, help_text='licht / middel / intensief / hoog_intensief', max_length=50),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='lvb_geschikt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='omschrijving_match_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='problematiek_types',
            field=models.JSONField(blank=True, default=list, help_text='Lijst van behandelde problematiek-types'),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='setting_type',
            field=models.CharField(blank=True, help_text='open / besloten / semi_besloten', max_length=50),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='trauma_geschikt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='veiligheidsrisico_hanteerbaar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='verslavingsproblematiek_mogelijk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='zorgdomein',
            field=models.CharField(blank=True, help_text='Zorgdomein: jeugd, volwassenen, lvb, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='zorgprofiel',
            name='zorgvorm',
            field=models.CharField(blank=True, help_text='Primaire zorgvorm: ambulant, residentieel, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='aanbiedervestiging',
            name='address',
            field=models.CharField(blank=True, help_text='Volledig adres (legacy/fallback)', max_length=500),
        ),
        migrations.AlterField(
            model_name='aanbiedervestiging',
            name='region',
            field=models.CharField(blank=True, help_text='Canonical regio code', max_length=100),
        ),
        migrations.AlterField(
            model_name='zorgprofiel',
            name='zorgaanbieder',
            field=models.ForeignKey(blank=True, help_text='Zorgaanbieder op organisatieniveau', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zorgprofielen', to='contracts.zorgaanbieder'),
        ),
        migrations.AddIndex(
            model_name='capaciteitrecord',
            index=models.Index(fields=['zorgprofiel', '-recorded_at'], name='provider_ca_zorgpro_28a90d_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgprofiel',
            index=models.Index(fields=['aanbieder_vestiging'], name='provider_zo_aanbied_4d6a14_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgprofiel',
            index=models.Index(fields=['zorgaanbieder'], name='provider_zo_zorgaan_2bf430_idx'),
        ),
        migrations.AddIndex(
            model_name='zorgprofiel',
            index=models.Index(fields=['zorgvorm'], name='provider_zo_zorgvor_7d1e3e_idx'),
        ),
        migrations.AddField(
            model_name='bronmappingissue',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_issues', to='contracts.providerimportbatch'),
        ),
        migrations.AddField(
            model_name='bronmappingissue',
            name='opgelost_door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opgeloste_mapping_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactpersoonaanbieder',
            name='aanbieder_vestiging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactpersonen', to='contracts.aanbiedervestiging'),
        ),
        migrations.AddField(
            model_name='contactpersoonaanbieder',
            name='zorgaanbieder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactpersonen', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='casus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_resultaten', to='contracts.carecase'),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='zorgaanbieder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_resultaten', to='contracts.zorgaanbieder'),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='zorgprofiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_resultaten', to='contracts.zorgprofiel'),
        ),
        migrations.AddField(
            model_name='prestatieprofiel',
            name='zorgprofiel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestatie_profiel', to='contracts.zorgprofiel'),
        ),
        migrations.AddIndex(
            model_name='bronmappingissue',
            index=models.Index(fields=['import_batch', 'opgelost'], name='provider_br_import__de3aad_idx'),
        ),
        migrations.AddIndex(
            model_name='bronmappingissue',
            index=models.Index(fields=['issue_type'], name='provider_br_issue_t_1852e3_idx'),
        ),
        migrations.AddIndex(
            model_name='contactpersoonaanbieder',
            index=models.Index(fields=['zorgaanbieder', 'actief'], name='provider_co_zorgaan_ab968a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresultaat',
            index=models.Index(fields=['casus', 'ranking'], name='provider_ma_casus_i_c4eeee_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresultaat',
            index=models.Index(fields=['zorgaanbieder', '-totaalscore'], name='provider_ma_zorgaan_4e3130_idx'),
        ),
        migrations.AddIndex(
            model_name='matchresultaat',
            index=models.Index(fields=['uitgesloten'], name='provider_ma_uitgesl_fb0c79_idx'),
        ),
    ]
