# Generated by Django 5.2.5 on 2026-04-18 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_provider_architecture_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bron_type', models.CharField(max_length=50)),
                ('batch_naam', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'In wachtrij'), ('RUNNING', 'Bezig'), ('COMPLETED', 'Voltooid'), ('PARTIAL', 'Deels voltooid'), ('FAILED', 'Mislukt')], default='PENDING', max_length=20)),
                ('gestart_op', models.DateTimeField(blank=True, null=True)),
                ('afgerond_op', models.DateTimeField(blank=True, null=True)),
                ('totaal_records', models.PositiveIntegerField(default=0)),
                ('geslaagd_records', models.PositiveIntegerField(default=0)),
                ('gefaald_records', models.PositiveIntegerField(default=0)),
                ('warnings_count', models.PositiveIntegerField(default=0)),
                ('foutenlog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bron_batch', to='contracts.providerimportbatch')),
            ],
            options={
                'db_table': 'provider_bronimportbatch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bronmappingissue',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_issues', to='contracts.bronimportbatch'),
        ),
        migrations.CreateModel(
            name='BronRecordRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_source', models.CharField(max_length=100)),
                ('external_id', models.CharField(db_index=True, max_length=200)),
                ('payload_json', models.JSONField()),
                ('record_hash', models.CharField(db_index=True, max_length=64)),
                ('normalisatie_status', models.CharField(default='PENDING', max_length=20)),
                ('foutmelding', models.TextField(blank=True)),
                ('verwerkt_op', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='contracts.bronimportbatch')),
            ],
            options={
                'db_table': 'provider_bronrecordraw',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BronSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bron_type', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('interne_entiteit_type', models.CharField(max_length=100)),
                ('interne_entiteit_id', models.CharField(blank=True, max_length=100)),
                ('actie', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('melding', models.TextField(blank=True)),
                ('uitgevoerd_op', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_bronsynclog',
                'ordering': ['-uitgevoerd_op'],
                'indexes': [models.Index(fields=['bron_type', '-uitgevoerd_op'], name='provider_br_bron_ty_5ed029_idx'), models.Index(fields=['interne_entiteit_type', 'interne_entiteit_id'], name='provider_br_interne_c924f2_idx'), models.Index(fields=['status'], name='provider_br_status_32a6ac_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='bronimportbatch',
            index=models.Index(fields=['bron_type', '-created_at'], name='provider_br_bron_ty_e48759_idx'),
        ),
        migrations.AddIndex(
            model_name='bronimportbatch',
            index=models.Index(fields=['status'], name='provider_br_status_1cf0f5_idx'),
        ),
        migrations.AddIndex(
            model_name='bronrecordraw',
            index=models.Index(fields=['import_batch', 'external_id'], name='provider_br_import__f32edc_idx'),
        ),
        migrations.AddIndex(
            model_name='bronrecordraw',
            index=models.Index(fields=['external_source'], name='provider_br_externa_33ecf2_idx'),
        ),
        migrations.AddIndex(
            model_name='bronrecordraw',
            index=models.Index(fields=['normalisatie_status'], name='provider_br_normali_9a0e74_idx'),
        ),
    ]
