# Generated by Django 5.2.5 on 2026-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_provider_bron_layer_and_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='preferred_region_type',
            field=models.CharField(
                choices=[
                    ('GEMEENTELIJK', 'Gemeentelijk'),
                    ('JEUGDREGIO', 'Jeugdregio'),
                    ('ROAZ', 'ROAZ'),
                    ('GGD', 'GGD'),
                    ('ZORGKANTOOR', 'Zorgkantoor'),
                ],
                default='GEMEENTELIJK',
                max_length=20,
                verbose_name='Voorkeur regiotype',
            ),
        ),
        migrations.AddField(
            model_name='municipalityconfiguration',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincie'),
        ),
        migrations.AddField(
            model_name='regionalconfiguration',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Provincie'),
        ),
        migrations.AlterField(
            model_name='regionalconfiguration',
            name='region_type',
            field=models.CharField(
                choices=[
                    ('GEMEENTELIJK', 'Gemeentelijk'),
                    ('JEUGDREGIO', 'Jeugdregio'),
                    ('ROAZ', 'ROAZ'),
                    ('GGD', 'GGD'),
                    ('ZORGKANTOOR', 'Zorgkantoor'),
                ],
                db_index=True,
                default='GEMEENTELIJK',
                max_length=20,
                verbose_name='Regiotype',
            ),
        ),
    ]
