# Generated by Django 5.2.5 on 2026-04-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0045_jeugdregio_backbone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='secondary_served_regions',
            field=models.ManyToManyField(blank=True, related_name='provider_profiles_secondary', to='contracts.regionalconfiguration', verbose_name="Secundaire bediende regio's"),
        ),
    ]
