# Generated by Django 5.2.5 on 2026-04-18 23:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_providerprofile_secondary_served_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseintakeprocess',
            name='contra_indicaties',
            field=models.TextField(blank=True, verbose_name='Contra-indicaties'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='gemeente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_processes', to='contracts.municipalityconfiguration', verbose_name='Gemeente'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='leeftijd',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Leeftijd (jaren)'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='max_toelaatbare_wachttijd_dagen',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximaal toelaatbare wachttijd (dagen)'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='problematiek_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Problematiektypes'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='regio',
            field=models.ForeignKey(blank=True, help_text='Deterministisch afgeleid uit gemeente; stabiel tenzij gemeente wijzigt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_intakes', to='contracts.regionalconfiguration', verbose_name='Geresolveerde regio'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='setting_voorkeur',
            field=models.CharField(blank=True, help_text='Bijv. open, besloten, semi_besloten, thuis.', max_length=50, verbose_name='Settingvoorkeur'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='zorgvorm_gewenst',
            field=models.CharField(blank=True, choices=[('OUTPATIENT', 'Ambulant'), ('DAY_TREATMENT', 'Dagbehandeling'), ('RESIDENTIAL', 'Residentieel'), ('CRISIS', 'Crisisopvang')], max_length=20, verbose_name='Zorgvorm gewenst (matching)'),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='score_capaciteit_wachttijd_fit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='score_complexiteit_veiligheid_fit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='score_performance_fit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchresultaat',
            name='score_regio_contract_fit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='casedecisionlog',
            name='event_type',
            field=models.CharField(choices=[('MATCH_RECOMMENDED', 'Match recommended'), ('PROVIDER_SELECTED', 'Provider selected'), ('RESEND_TRIGGERED', 'Resend triggered'), ('PROVIDE_MISSING_INFO', 'Missing info provided'), ('REMATCH_TRIGGERED', 'Rematch triggered'), ('CONTINUE_WAITING', 'Continue waiting'), ('SLA_ESCALATION', 'SLA state transition'), ('CASE_COMMUNICATION', 'Case communication')], max_length=40),
        ),
        migrations.CreateModel(
            name='ProviderRegioDekking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primair_dekkingsgebied', models.BooleanField(default=True)),
                ('zorgvormen', models.JSONField(blank=True, default=list)),
                ('doelgroepen', models.JSONField(blank=True, default=list)),
                ('contract_actief', models.BooleanField(default=True)),
                ('capaciteit_meerekenen', models.BooleanField(default=True)),
                ('reisafstand_score', models.FloatField(default=1.0, help_text='0.0–1.0 score voor bereikbaarheid/reisafstand.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('dekking_status', models.CharField(choices=[('ACTIVE', 'Actief'), ('INACTIVE', 'Inactief'), ('DRAFT', 'Concept'), ('SUSPENDED', 'Opgeschort')], default='ACTIVE', max_length=20)),
                ('toelichting', models.TextField(blank=True)),
                ('bron_type', models.CharField(choices=[('manual', 'Handmatig ingevoerd'), ('seeded', 'Seed data'), ('csv_import', 'CSV import'), ('api', 'API synchronisatie')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aanbieder_vestiging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regio_dekkingen', to='contracts.aanbiedervestiging')),
                ('regio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_dekkingen', to='contracts.regionalconfiguration')),
                ('zorgaanbieder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regio_dekkingen', to='contracts.zorgaanbieder')),
            ],
            options={
                'db_table': 'provider_regiodekking',
                'ordering': ['-is_primair_dekkingsgebied', 'regio__region_name', '-updated_at'],
                'indexes': [models.Index(fields=['zorgaanbieder', 'regio', 'dekking_status'], name='provider_re_zorgaan_81f0f5_idx'), models.Index(fields=['regio', 'contract_actief'], name='provider_re_regio_i_9ef619_idx')],
                'unique_together': {('zorgaanbieder', 'aanbieder_vestiging', 'regio')},
            },
        ),
    ]
