# Generated by Django 5.2.5 on 2026-04-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_caseintakeprocess_contra_indicaties_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseintakeprocess',
            name='arrangement_end_date',
            field=models.DateField(blank=True, help_text='Verwachte of bevestigde einddatum van het zorgtraject.', null=True, verbose_name='Einddatum arrangement'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='arrangement_provider',
            field=models.CharField(blank=True, help_text='Naam of referentie van de aanbieder die het arrangement uitvoert.', max_length=200, verbose_name='Arrangementaanbieder'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='arrangement_type_code',
            field=models.CharField(blank=True, help_text='Bijv. ZIN-dagbehandeling, PGB-ambulant.', max_length=100, verbose_name='Arrangementcode'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='urgency_document',
            field=models.FileField(blank=True, help_text='Verplicht voordat urgentie kan worden gevalideerd.', null=True, upload_to='urgency_documents/%Y/%m/', verbose_name='Urgentieverklaring'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='urgency_granted_date',
            field=models.DateField(blank=True, help_text='Datum waarop urgentie door gemeente is vastgesteld. Bepaalt prioriteitsvolgorde bij urgente casussen.', null=True, verbose_name='Datum urgentieverlening'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='urgency_validated',
            field=models.BooleanField(default=False, help_text='Mag alleen worden ingesteld door gemeente, en alleen als urgentieverklaring is bijgevoegd.', verbose_name='Urgentie gevalideerd'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='urgency_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Urgentie gevalideerd op'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='urgency_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_urgencies', to=settings.AUTH_USER_MODEL, verbose_name='Urgentie gevalideerd door'),
        ),
    ]
