# Generated by Django 5.2.5 on 2026-04-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_urgency_validation_and_arrangement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecase',
            name='case_phase',
            field=models.CharField(choices=[('intake', 'Intake'), ('matching', 'Matching'), ('provider_beoordeling', 'Aanbiederbeoordeling'), ('plaatsing', 'Plaatsing'), ('actief', 'Actief'), ('afgerond', 'Afgerond')], default='intake', max_length=20),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='status',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('MATCHING', 'Matching'), ('DECISION', 'Matchbesluit'), ('COMPLETED', 'Afgerond'), ('ON_HOLD', 'In wacht')], default='INTAKE', max_length=20, verbose_name='Status'),
        ),
    ]
