# Generated by Django 5.2.13 on 2026-04-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_remove_beoordeling_phase_add_provider_beoordeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('urgent_unmatched_case', 'Urgente casus zonder match'), ('incomplete_beoordeling', 'Onvolledige beoordeling'), ('missing_critical_data', 'Kritieke data ontbreekt'), ('weak_match_needs_review', 'Zwakke match – review vereist'), ('placement_stalled', 'Plaatsing stagneert'), ('provider_capacity_risk', 'Capaciteitsrisico aanbieder')], max_length=40, verbose_name='Alert type')),
                ('severity', models.CharField(choices=[('high', 'Hoog'), ('medium', 'Middel'), ('low', 'Laag')], default='medium', max_length=10, verbose_name='Ernst')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Omschrijving')),
                ('recommended_action', models.TextField(verbose_name='Aanbevolen actie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Opgelost op')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alerts', to='contracts.caseintakeprocess', verbose_name='Casus')),
            ],
            options={
                'verbose_name': 'Operationeel alert',
                'verbose_name_plural': 'Operationele alerts',
                'db_table': 'contracts_operationalalert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'alert_type', 'resolved_at'], name='contracts_o_case_id_4b1dfe_idx'), models.Index(fields=['severity', 'resolved_at'], name='contracts_o_severit_328083_idx')],
            },
        ),
    ]
