# Generated by Django 5.2.13 on 2026-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_remove_beoordeling_phase_add_provider_beoordeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecase',
            name='case_phase',
            field=models.CharField(choices=[('intake', 'Intake'), ('beoordeling', 'Beoordeling'), ('matching', 'Matching'), ('provider_beoordeling', 'Aanbiederbeoordeling'), ('plaatsing', 'Plaatsing'), ('actief', 'Actief'), ('afgerond', 'Afgerond')], default='intake', max_length=20),
        ),
        migrations.AlterField(
            model_name='casedecisionlog',
            name='event_type',
            field=models.CharField(choices=[('MATCH_RECOMMENDED', 'Match recommended'), ('PROVIDER_SELECTED', 'Provider selected'), ('RESEND_TRIGGERED', 'Resend triggered'), ('PROVIDE_MISSING_INFO', 'Missing info provided'), ('REMATCH_TRIGGERED', 'Rematch triggered'), ('CONTINUE_WAITING', 'Continue waiting'), ('SLA_ESCALATION', 'SLA state transition'), ('CASE_COMMUNICATION', 'Case communication'), ('INTELLIGENCE_EVALUATED', 'Intelligence evaluated')], max_length=40),
        ),
    ]
