# Generated by Django 5.2.5 on 2026-04-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_remove_beoordeling_phase_add_provider_beoordeling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carecase',
            name='lifecycle_stage',
            field=models.CharField(choices=[('DRAFTING', 'Voorbereiding'), ('INTERNAL_REVIEW', 'Interne beoordeling'), ('NEGOTIATION', 'Afstemming'), ('APPROVAL', 'Indicatie'), ('SIGNATURE', 'Bevestiging'), ('EXECUTED', 'Gestart'), ('OBLIGATION_TRACKING', 'Voortgangsbewaking'), ('RENEWAL', 'Herbeoordeling / afronding'), ('ARCHIVED', 'Gearchiveerd')], default='DRAFTING', max_length=20),
        ),
        migrations.AlterField(
            model_name='caseassessment',
            name='assessment_status',
            field=models.CharField(choices=[('DRAFT', 'Concept'), ('UNDER_REVIEW', 'In beoordeling door aanbieder'), ('APPROVED_FOR_MATCHING', 'Goedgekeurd voor matching'), ('NEEDS_INFO', 'Aanvullende info nodig')], default='DRAFT', max_length=32, verbose_name='Beoordeling door aanbieder status'),
        ),
        migrations.AlterField(
            model_name='casedecisionlog',
            name='event_type',
            field=models.CharField(choices=[('MATCH_RECOMMENDED', 'Match recommended'), ('PROVIDER_SELECTED', 'Provider selected'), ('RESEND_TRIGGERED', 'Resend triggered'), ('PROVIDE_MISSING_INFO', 'Missing info provided'), ('REMATCH_TRIGGERED', 'Rematch triggered'), ('CONTINUE_WAITING', 'Continue waiting'), ('SLA_ESCALATION', 'SLA state transition'), ('CASE_COMMUNICATION', 'Case communication'), ('STATE_TRANSITION', 'Workflow state transition')], max_length=40),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='status',
            field=models.CharField(choices=[('INTAKE', 'Intake'), ('MATCHING', 'Matching'), ('DECISION', 'Matchbesluit'), ('COMPLETED', 'Afgerond'), ('ON_HOLD', 'In wacht'), ('ARCHIVED', 'Gearchiveerd')], default='INTAKE', max_length=20, verbose_name='Status'),
        ),
    ]
