# Generated by Django 5.2.13 on 2026-04-20 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_remove_beoordeling_phase_add_provider_beoordeling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveIntegerField(default=42, verbose_name='Seed (reproduceerbaar)')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Label')),
                ('status', models.CharField(choices=[('RUNNING', 'Bezig'), ('COMPLETED', 'Afgerond'), ('FAILED', 'Mislukt')], default='RUNNING', max_length=20, verbose_name='Status')),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('successful_flows', models.PositiveIntegerField(default=0)),
                ('blocked_missing_data', models.PositiveIntegerField(default=0)),
                ('blocked_no_capacity', models.PositiveIntegerField(default=0)),
                ('weak_match_count', models.PositiveIntegerField(default=0)),
                ('stalled_placement_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Samenvatting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='contracts.organization')),
            ],
            options={
                'verbose_name': 'Simulatieronde',
                'verbose_name_plural': 'Simulatierondes',
                'db_table': 'contracts_simulationrun',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.PositiveSmallIntegerField(verbose_name='Casusnummer (1-50)')),
                ('current_phase', models.CharField(choices=[('INTAKE', 'Intake'), ('BEOORDELING', 'Beoordeling'), ('MATCHING', 'Matching'), ('PLAATSING', 'Plaatsing'), ('INTAKE_OVERDRACHT', 'Intake overdracht'), ('AFGEROND', 'Afgerond'), ('GEBLOKKEERD', 'Geblokkeerd')], default='INTAKE', max_length=30)),
                ('next_best_action', models.CharField(blank=True, max_length=300)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('matched_provider_count', models.PositiveSmallIntegerField(default=0)),
                ('placement_status', models.CharField(blank=True, max_length=30)),
                ('pipeline_block_reason', models.CharField(choices=[('NONE', 'Geen'), ('MISSING_DATA', 'Ontbrekende data'), ('NO_CAPACITY', 'Geen capaciteit'), ('NO_PROVIDERS', 'Geen aanbieders gevonden'), ('WEAK_MATCH', 'Zwakke match'), ('STALLED_PLACEMENT', 'Plaatsing vastgelopen'), ('URGENT_LIMITED', 'Urgent, beperkt aanbod')], default='NONE', max_length=30)),
                ('urgency_snapshot', models.CharField(blank=True, max_length=10)),
                ('complexity_snapshot', models.CharField(blank=True, max_length=20)),
                ('age_group_snapshot', models.CharField(blank=True, max_length=10)),
                ('care_category_snapshot', models.CharField(blank=True, max_length=100)),
                ('region_snapshot', models.CharField(blank=True, max_length=150)),
                ('has_missing_fields', models.BooleanField(default=False)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_results', to='contracts.caseintakeprocess')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_results', to='contracts.placementrequest')),
                ('selected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_selections', to='contracts.client')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='contracts.simulationrun')),
            ],
            options={
                'verbose_name': 'Gesimuleerde casus',
                'verbose_name_plural': 'Gesimuleerde casussen',
                'db_table': 'contracts_simulatedcaseresult',
                'ordering': ['run', 'case_number'],
            },
        ),
    ]
