# Generated by Django 5.2.13 on 2026-04-20 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_simulation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegiekamerAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('urgent_unmatched_case', 'Urgente casus zonder match'), ('missing_critical_data', 'Ontbrekende kritieke gegevens'), ('incomplete_beoordeling', 'Onvolledige beoordeling'), ('weak_match_needs_review', 'Zwakke match – review vereist'), ('no_capacity_available', 'Geen capaciteit beschikbaar'), ('placement_stalled', 'Plaatsing vastgelopen')], db_index=True, max_length=40, verbose_name='Type alert')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Kritiek'), ('HIGH', 'Hoog'), ('MEDIUM', 'Middel'), ('LOW', 'Laag')], db_index=True, default='MEDIUM', max_length=10, verbose_name='Prioriteit')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Omschrijving')),
                ('recommended_action', models.TextField(blank=True, verbose_name='Aanbevolen actie')),
                ('source_phase', models.CharField(blank=True, max_length=30, verbose_name='Bron fase')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='Afgehandeld')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Afgehandeld op')),
                ('auto_resolved', models.BooleanField(default=False, help_text='True when resolved because the underlying case condition changed.', verbose_name='Automatisch afgehandeld')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiekamer_alerts', to='contracts.caseintakeprocess', verbose_name='Casus')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regiekamer_alerts', to='contracts.organization')),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regiekamer_alerts', to='contracts.placementrequest', verbose_name='Plaatsing')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Afgehandeld door')),
            ],
            options={
                'verbose_name': 'Regiekamer Alert',
                'verbose_name_plural': 'Regiekamer Alerts',
                'db_table': 'contracts_regiekameralert',
                'ordering': ['-severity', 'created_at'],
                'indexes': [models.Index(fields=['organization', 'is_resolved', 'severity'], name='contracts_r_organiz_922557_idx'), models.Index(fields=['case', 'alert_type', 'is_resolved'], name='contracts_r_case_id_7412a8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('case', 'alert_type'), name='unique_open_alert_per_case_type')],
            },
        ),
    ]
