# Generated by Django 5.2.5 on 2026-04-25 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_alter_carecase_lifecycle_stage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caresignal',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Signaal', 'verbose_name_plural': 'Signalen'},
        ),
    ]
