# Generated by Django 5.2.13 on 2026-04-20 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_provider_evaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalalert',
            name='alert_type',
            field=models.CharField(choices=[('urgent_unmatched_case', 'Urgente casus zonder match'), ('incomplete_beoordeling', 'Onvolledige beoordeling'), ('missing_critical_data', 'Kritieke data ontbreekt'), ('weak_match_needs_review', 'Zwakke match – review vereist'), ('placement_stalled', 'Plaatsing stagneert'), ('provider_capacity_risk', 'Capaciteitsrisico aanbieder'), ('provider_info_requested', 'Informatieverzoek aanbieder'), ('provider_info_stale', 'Informatieverzoek verlopen')], max_length=40, verbose_name='Alert type'),
        ),
        migrations.CreateModel(
            name='CaseInformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_info_text', models.TextField(help_text='Wat de aanbieder wil weten voordat een besluit kan worden genomen.', verbose_name='Gevraagde informatie')),
                ('requested_fields', models.JSONField(blank=True, default=list, help_text='Optionele gestructureerde lijst van specifiek gevraagde velden of ontbrekende documenten.', verbose_name='Gevraagde velden')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In behandeling'), ('resolved', 'Opgelost'), ('resubmitted', 'Herindienen')], default='open', max_length=20, verbose_name='Status')),
                ('operator_response', models.TextField(blank=True, help_text='Door de operator aangeleverde informatie als reactie op het verzoek.', verbose_name='Reactie operator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Opgelost op')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='contracts.caseintakeprocess', verbose_name='Casus')),
                ('evaluation', models.ForeignKey(blank=True, help_text='De aanbiederbeoordeling die dit verzoek heeft getriggerd.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_requests', to='contracts.providerevaluation', verbose_name='Beoordeling')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='contracts.client', verbose_name='Aanbieder')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_information_requests', to=settings.AUTH_USER_MODEL, verbose_name='Opgelost door')),
            ],
            options={
                'verbose_name': 'Informatieverzoek',
                'verbose_name_plural': 'Informatieverzoeken',
                'db_table': 'contracts_caseinformationrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'status'], name='contracts_c_case_id_469758_idx'), models.Index(fields=['provider', '-created_at'], name='contracts_c_provide_464b79_idx'), models.Index(fields=['status', '-created_at'], name='contracts_c_status_affddb_idx')],
            },
        ),
    ]
