# Generated by Django 5.2.13 on 2026-04-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0051_regiekamer_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiekameralert',
            name='evidence_data',
            field=models.JSONField(blank=True, help_text='V3 structured evidence: fit_summary, confidence, factor_breakdown, trade_offs, verification_guidance, provider_feedback.', null=True, verbose_name='Beslissingsonderbouwing'),
        ),
        migrations.AddField(
            model_name='regiekameralert',
            name='rejection_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of provider rejections for this case (used to escalate priority).', verbose_name='Aantal afwijzingen'),
        ),
        migrations.AddField(
            model_name='regiekameralert',
            name='rejection_reason_code',
            field=models.CharField(blank=True, help_text='Reason code provided by the provider when rejecting the case.', max_length=60, verbose_name='Reden afwijzing'),
        ),
        migrations.AlterField(
            model_name='regiekameralert',
            name='alert_type',
            field=models.CharField(choices=[('urgent_unmatched_case', 'Urgente casus zonder match'), ('missing_critical_data', 'Ontbrekende kritieke gegevens'), ('missing_summary', 'Samenvatting ontbreekt'), ('summary_missing_or_stale', 'Samenvatting verouderd of incompleet'), ('weak_match_needs_verification', 'Zwakke match – verificatie vereist'), ('provider_review_pending', 'Aanbieder beoordeling wacht op actie'), ('provider_rejected_case', 'Casus afgewezen door aanbieder'), ('provider_capacity_risk', 'Capaciteitsrisico bij aanbieder'), ('no_capacity_available', 'Geen capaciteit beschikbaar'), ('placement_stalled', 'Plaatsing vastgelopen'), ('intake_not_started', 'Intake nog niet gestart'), ('incomplete_beoordeling', 'Onvolledige beoordeling (verouderd)'), ('weak_match_needs_review', 'Zwakke match – review vereist (verouderd)')], db_index=True, max_length=40, verbose_name='Type alert'),
        ),
    ]
