# Generated by Django 5.2.13 on 2026-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0052_v3_alert_types_and_evidence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrequest',
            name='predicted_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score van de V3 intelligence op het moment van aanbiedersselectie (0.0–1.0).', null=True, verbose_name='Voorspeld vertrouwensniveau'),
        ),
    ]
