# Generated by Django 5.2.13 on 2026-04-20 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_predicted_confidence_placement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TuningProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUGGESTED', 'Voorgesteld'), ('REVIEWED', 'Beoordeeld'), ('APPROVED', 'Goedgekeurd'), ('REJECTED', 'Afgewezen'), ('IMPLEMENTED', 'Geïmplementeerd')], db_index=True, default='SUGGESTED', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('high_conf_low_accept', 'Hoog vertrouwen / lage acceptatie'), ('low_conf_high_success', 'Laag vertrouwen / hoog succes'), ('category_drift', 'Zorgcategorie drift'), ('provider_drift', 'Aanbieder drift'), ('taxonomy_cluster', 'Afwijzingstaxonomie cluster'), ('manual', 'Handmatig')], default='manual', max_length=40, verbose_name='Bron')),
                ('factor_type', models.CharField(choices=[('SPECIALIZATION_WEIGHT', 'Specialisatiegewicht'), ('PROVIDER_RELIABILITY_BOOST', 'Aanbieder betrouwbaarheidsbonus'), ('CAPACITY_REJECTION_PENALTY', 'Capaciteitsafwijzingspenalty'), ('CATEGORY_CONFIDENCE_THRESHOLD', 'Categorie confidence-drempel'), ('REGION_WEIGHT', 'Regiogewicht'), ('COMPLEXITY_THRESHOLD', 'Complexiteitsdrempel'), ('OTHER', 'Overig')], max_length=40, verbose_name='Factor')),
                ('detected_issue', models.TextField(help_text='Beschrijving van de kalibratie-anomalie die dit voorstel triggerde.', verbose_name='Gedetecteerd probleem')),
                ('recommendation', models.TextField(help_text='Adviserende omschrijving van de gewenste aanpassing.', verbose_name='Aanbeveling')),
                ('proposed_delta', models.FloatField(blank=True, help_text='Indicatieve numerieke gewichtsaanpassing (bijv. +0.10 of -0.05). Puur adviserend; wordt nooit automatisch toegepast.', null=True, verbose_name='Voorgestelde delta')),
                ('rationale', models.TextField(blank=True, default='', help_text='Aanvullende toelichting of context bij het voorstel.', verbose_name='Onderbouwing')),
                ('simulation_before', models.JSONField(blank=True, help_text="Verwachte confidence/ranking vóór aanpassing (snapshot van voorbeeldscenario's).", null=True, verbose_name='Simulatie voor')),
                ('simulation_after', models.JSONField(blank=True, help_text="Verwachte confidence/ranking ná aanpassing (snapshot van voorbeeldscenario's).", null=True, verbose_name='Simulatie na')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Beoordeeld op')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='Beoordelingsnotitie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_care_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuning_proposals', to='contracts.carecategorymain', verbose_name='Zorgcategorie')),
                ('affected_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuning_proposals', to='contracts.client', verbose_name='Aanbieder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tuning_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Aangemaakt door')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuning_proposals', to='contracts.organization', verbose_name='Organisatie')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tuning_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Beoordeeld door')),
            ],
            options={
                'verbose_name': 'Tuningvoorstel',
                'verbose_name_plural': 'Tuningvoorstellen',
                'db_table': 'contracts_tuningproposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='contracts_t_organiz_f98460_idx'), models.Index(fields=['status', 'created_at'], name='contracts_t_status_145f92_idx')],
            },
        ),
    ]
