# Generated by Django 5.2.13 on 2026-04-20 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0054_tuning_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tuningproposal',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Deterministische sleutel voor deduplicatie en groepering van vergelijkbare voorstellen over meerdere kalibratie-runs. Formaat: "<source>|<factor_type>|<scope>".', max_length=120, verbose_name='Groepsleutel'),
        ),
        migrations.AddField(
            model_name='tuningproposal',
            name='implemented_at',
            field=models.DateTimeField(blank=True, help_text='Tijdstip waarop de status op IMPLEMENTED werd gezet.', null=True, verbose_name='Geïmplementeerd op'),
        ),
        migrations.AddField(
            model_name='tuningproposal',
            name='post_impact',
            field=models.JSONField(blank=True, help_text='Vergelijking van uitkomsten voor en na implementatie. Bevat before_mean_confidence, after_mean_confidence, delta_observed, acceptance_rate_before, acceptance_rate_after en sample_count.', null=True, verbose_name='Post-implementatie impact'),
        ),
        migrations.AddField(
            model_name='tuningproposal',
            name='priority_score',
            field=models.FloatField(blank=True, help_text='Adviserende prioriteitsscore 0–1 berekend op basis van ernst, steekproefomvang en verwachte impact van de delta. Hoger = hogere prioriteit.', null=True, verbose_name='Prioriteitsscore'),
        ),
        migrations.AddField(
            model_name='tuningproposal',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Laag risico'), ('HIGH', 'Hoog risico')], default='LOW', help_text='Hoog risico wanneer |delta| > 0.15 of het voorstel aanbiedersspecifiek is. Puur adviserend; geen effect op workflowlogica.', max_length=4, verbose_name='Risiconiveau'),
        ),
        migrations.AddField(
            model_name='tuningproposal',
            name='sample_count',
            field=models.PositiveIntegerField(blank=True, help_text='Aantal plaatsingsrijen waarop dit voorstel is gebaseerd.', null=True, verbose_name='Steekproefomvang'),
        ),
        migrations.AddIndex(
            model_name='tuningproposal',
            index=models.Index(fields=['organization', 'group_key'], name='contracts_t_organiz_62265b_idx'),
        ),
    ]
