# Generated by Django 5.2.13 on 2026-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0056_caseassessment_workflow_summary_and_validation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedecisionlog',
            name='event_type',
            field=models.CharField(choices=[('MATCH_RECOMMENDED', 'Match recommended'), ('PROVIDER_SELECTED', 'Provider selected'), ('RESEND_TRIGGERED', 'Resend triggered'), ('PROVIDE_MISSING_INFO', 'Missing info provided'), ('REMATCH_TRIGGERED', 'Rematch triggered'), ('CONTINUE_WAITING', 'Continue waiting'), ('SLA_ESCALATION', 'SLA state transition'), ('CASE_COMMUNICATION', 'Case communication'), ('STATE_TRANSITION', 'Workflow state transition'), ('GEMEENTE_VALIDATION', 'Gemeente validatie matching')], max_length=40),
        ),
    ]
