# Generated by Django 5.2.13 on 2026-05-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0057_alter_casedecisionlog_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GEMEENTE_VALIDATION_APPROVED', 'Gemeente validatie afgerond'), ('PLACEMENT_REQUEST_CREATED', 'Plaatsingsaanvraag vastgelegd'), ('PROVIDER_REVIEW_OPENED', 'Aanbiederbeoordeling geopend'), ('WORKFLOW_BLOCKED', 'Workflow geblokkeerd'), ('WORKFLOW_ESCALATED', 'Workflow escalatie')], max_length=80)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('source', models.CharField(blank=True, help_text='Origin surface (e.g. matching_action_api).', max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('release_id', models.CharField(blank=True, max_length=120)),
                ('build_sha', models.CharField(blank=True, max_length=64)),
                ('from_phase', models.CharField(blank=True, max_length=40)),
                ('to_phase', models.CharField(blank=True, max_length=40)),
                ('reason_code', models.CharField(blank=True, max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_timeline_events', to='contracts.auditlog')),
                ('care_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='contracts.carecase')),
                ('decision_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='contracts.casedecisionlog')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_timeline_events', to='contracts.organization')),
            ],
            options={
                'db_table': 'contracts_casetimelineevent',
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['care_case', 'occurred_at'], name='contracts_c_care_ca_a0aff5_idx'), models.Index(fields=['organization', 'occurred_at'], name='contracts_c_organiz_77782b_idx')],
            },
        ),
    ]
