# Generated by Django 5.2.13 on 2026-06-17 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_complexity_and_risk(apps, schema_editor):
    """
    Data migration:
    - CaseIntakeProcess.complexity: SIMPLE→ENKELVOUDIG, MULTIPLE→MEERVOUDIG,
      SEVERE→(complexity='', care_intensity='INTENSIEF', status=NEEDS_REVIEW)
    - CareCase.risk_level: LOW/MEDIUM→GEEN_BIJZONDER_RISICO, HIGH→VERHOOGD_RISICO, CRITICAL→ACUUT_RISICO
    - ProviderProfile: handles_severe copied to handles_high_complex
    """
    CaseIntakeProcess = apps.get_model('contracts', 'CaseIntakeProcess')
    CareCase = apps.get_model('contracts', 'CareCase')

    # Complexity value mapping
    complexity_map = {
        'SIMPLE': 'ENKELVOUDIG',
        'MULTIPLE': 'MEERVOUDIG',
    }

    for intake in CaseIntakeProcess.objects.all():
        if intake.complexity in complexity_map:
            intake.complexity = complexity_map[intake.complexity]
            intake.complexity_status = 'SYSTEM_PROPOSED'
            intake.save(update_fields=['complexity', 'complexity_status'])
        elif intake.complexity == 'SEVERE':
            # SEVERE = "Intensief" in de UI → wordt nu zorgintensiteit, niet complexiteit
            intake.complexity = ''
            intake.care_intensity = 'INTENSIEF'
            intake.complexity_status = 'NEEDS_REVIEW'
            intake.care_intensity_status = 'NEEDS_REVIEW'
            intake.save(update_fields=['complexity', 'care_intensity', 'complexity_status', 'care_intensity_status'])

    # Risk level mapping
    risk_map = {
        'LOW': 'GEEN_BIJZONDER_RISICO',
        'MEDIUM': 'GEEN_BIJZONDER_RISICO',
        'HIGH': 'VERHOOGD_RISICO',
        'CRITICAL': 'ACUUT_RISICO',
    }
    for case in CareCase.objects.all():
        new_risk = risk_map.get(case.risk_level)
        if new_risk:
            case.risk_level = new_risk
            case.save(update_fields=['risk_level'])


def reverse_migration(apps, schema_editor):
    pass  # Lossy migration — no automatic reverse


class Migration(migrations.Migration):
    atomic = False  # SQLite: ForeignKey index creation fails with pending trigger events inside one transaction

    dependencies = [
        ('contracts', '0086_caseintakeprocess_placement_pressure_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='handles_severe',
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='care_intensity',
            field=models.CharField(blank=True, choices=[('LICHT', 'Licht'), ('REGULIER', 'Regulier'), ('INTENSIEF', 'Intensief')], default='', max_length=10, verbose_name='Zorgintensiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='care_intensity_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Zorgintensiteit bevestigd op'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='care_intensity_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_care_intensities', to=settings.AUTH_USER_MODEL, verbose_name='Zorgintensiteit bevestigd door'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='care_intensity_override_reason',
            field=models.TextField(blank=True, default='', verbose_name='Reden wijziging zorgintensiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='care_intensity_status',
            field=models.CharField(choices=[('SYSTEM_PROPOSED', 'Systeemvoorstel'), ('CONFIRMED', 'Professioneel bevestigd'), ('OVERRIDDEN', 'Professioneel gewijzigd'), ('NEEDS_REVIEW', 'Nog te beoordelen')], default='SYSTEM_PROPOSED', max_length=20, verbose_name='Status zorgintensiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='classification_rationale',
            field=models.JSONField(blank=True, help_text='Criteria en uitleg van het systeemvoorstel.', null=True, verbose_name='Classificatie-onderbouwing'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='complexity_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Complexiteit bevestigd op'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='complexity_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_complexities', to=settings.AUTH_USER_MODEL, verbose_name='Complexiteit bevestigd door'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='complexity_override_reason',
            field=models.TextField(blank=True, default='', verbose_name='Reden wijziging complexiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='complexity_status',
            field=models.CharField(choices=[('SYSTEM_PROPOSED', 'Systeemvoorstel'), ('CONFIRMED', 'Professioneel bevestigd'), ('OVERRIDDEN', 'Professioneel gewijzigd'), ('NEEDS_REVIEW', 'Nog te beoordelen')], default='SYSTEM_PROPOSED', max_length=20, verbose_name='Status complexiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='proposed_care_intensity',
            field=models.CharField(blank=True, choices=[('LICHT', 'Licht'), ('REGULIER', 'Regulier'), ('INTENSIEF', 'Intensief')], default='', max_length=10, verbose_name='Voorgestelde zorgintensiteit'),
        ),
        migrations.AddField(
            model_name='caseintakeprocess',
            name='proposed_complexity',
            field=models.CharField(blank=True, choices=[('ENKELVOUDIG', 'Enkelvoudig'), ('MEERVOUDIG', 'Meervoudig'), ('HOOGCOMPLEX', 'Hoogcomplex')], default='', max_length=15, verbose_name='Voorgestelde complexiteit'),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='handles_high_complex',
            field=models.BooleanField(default=False, verbose_name='Kan: Hoogcomplex'),
        ),
        migrations.AlterField(
            model_name='carecase',
            name='risk_level',
            field=models.CharField(choices=[('GEEN_BIJZONDER_RISICO', 'Geen bijzonder risico'), ('VERHOOGD_RISICO', 'Verhoogd risico'), ('ACUUT_RISICO', 'Acuut risico')], default='GEEN_BIJZONDER_RISICO', max_length=25),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='complexity',
            field=models.CharField(blank=True, choices=[('ENKELVOUDIG', 'Enkelvoudig'), ('MEERVOUDIG', 'Meervoudig'), ('HOOGCOMPLEX', 'Hoogcomplex')], default='', max_length=15, verbose_name='Complexiteit'),
        ),
        migrations.AlterField(
            model_name='caseintakeprocess',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Laag'), ('MEDIUM', 'Normaal'), ('HIGH', 'Hoog'), ('CRISIS', 'Crisis')], default='MEDIUM', max_length=10, verbose_name='Urgentie'),
        ),
        migrations.RunPython(migrate_complexity_and_risk, reverse_code=reverse_migration),
    ]
