"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _bool_env(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv_env(name: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return list(default or [])
    return [item.strip() for item in raw.split(',') if item.strip()]


def _invalid_database_url(message: str) -> ImproperlyConfigured:
    return ImproperlyConfigured(
        f"{message} Expected format: "
        "postgresql://USER:PASSWORD@HOST:5432/DBNAME?sslmode=require"
    )


def _database_config() -> dict[str, object]:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if not database_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    if scheme in {'postgres', 'postgresql'}:
        query = parse_qs(parsed.query)
        try:
            port = parsed.port
        except ValueError as exc:
            raise _invalid_database_url(
                'DATABASE_URL has an invalid port value. Do not use placeholder text like "port".'
            ) from exc

        database_name = parsed.path.lstrip('/')
        if not parsed.hostname or not database_name:
            raise _invalid_database_url(
                'DATABASE_URL is missing a hostname or database name.'
            )

        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': database_name,
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or '',
            'PORT': str(port or '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                'sslmode': query.get('sslmode', ['require'])[0],
            },
        }

    if scheme == 'sqlite':
        sqlite_path = parsed.path or '/db.sqlite3'
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(sqlite_path),
        }

    raise _invalid_database_url(
        f'DATABASE_URL uses unsupported scheme {parsed.scheme!r}. Use postgresql:// or postgres://.'
    )


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    os.getenv('SECRET_KEY', 'django-insecure-h4dao*+381s=dgr2v6+1!#%ui6bz4#f95*hfcq!m73vn!^#)u&'),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_env('DJANGO_DEBUG', default=_bool_env('DEBUG', default=True))

ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', default=['*'])

CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'https://*.replit.dev',
        'https://*.repl.co',
        'https://*.riker.replit.dev',
        'https://*.riker.replit.dev:8000',
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'theme',
    'contracts',
]

if DEBUG:
    INSTALLED_APPS.extend([
        'django_browser_reload',
        'debug_toolbar',
    ])


SSO_ENABLED = _bool_env('SSO_ENABLED', default=False)

try:
    import mozilla_django_oidc  # noqa: F401
    OIDC_PACKAGE_AVAILABLE = True
except Exception:
    OIDC_PACKAGE_AVAILABLE = False

if OIDC_PACKAGE_AVAILABLE:
    INSTALLED_APPS.append('mozilla_django_oidc')

if SSO_ENABLED and not OIDC_PACKAGE_AVAILABLE:
    raise ImportError(
        'SSO_ENABLED is true but mozilla-django-oidc is not installed. '
        'Install it with: pip install mozilla-django-oidc'
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'contracts.middleware.OrganizationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(2, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contracts.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': _database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'theme' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Feature Flags
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@careon.local')
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _bool_env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if SSO_ENABLED:
    AUTHENTICATION_BACKENDS.insert(0, 'contracts.auth_backends.CareonOIDCAuthenticationBackend')

OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID', '')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET', '')
OIDC_RP_SIGN_ALGO = os.getenv('OIDC_RP_SIGN_ALGO', 'RS256')
# Keep as a space-delimited string to match mozilla-django-oidc expectations.
OIDC_RP_SCOPES = os.getenv('OIDC_RP_SCOPES', 'openid email profile')
SSO_ALLOWED_EMAIL_DOMAINS = [
    d.strip().lower()
    for d in os.getenv('SSO_ALLOWED_EMAIL_DOMAINS', '').split(',')
    if d.strip()
]

OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_OP_AUTHORIZATION_ENDPOINT', '')
OIDC_OP_TOKEN_ENDPOINT = os.getenv('OIDC_OP_TOKEN_ENDPOINT', '')
OIDC_OP_USER_ENDPOINT = os.getenv('OIDC_OP_USER_ENDPOINT', '')
OIDC_OP_JWKS_ENDPOINT = os.getenv('OIDC_OP_JWKS_ENDPOINT', '')
OIDC_OP_LOGOUT_ENDPOINT = os.getenv('OIDC_OP_LOGOUT_ENDPOINT', '')
OIDC_OP_DISCOVERY_ENDPOINT = os.getenv('OIDC_OP_DISCOVERY_ENDPOINT', '')

OIDC_USE_NONCE = True
OIDC_STORE_ACCESS_TOKEN = False
OIDC_VERIFY_SSL = _bool_env('OIDC_VERIFY_SSL', default=True)

if SSO_ENABLED:
    has_discovery = bool(OIDC_OP_DISCOVERY_ENDPOINT)
    has_explicit_endpoints = all([
        OIDC_OP_AUTHORIZATION_ENDPOINT,
        OIDC_OP_TOKEN_ENDPOINT,
        OIDC_OP_USER_ENDPOINT,
        OIDC_OP_JWKS_ENDPOINT,
    ])

    if not (OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET and (has_discovery or has_explicit_endpoints)):
        raise ImportError(
            'SSO_ENABLED is true but required OIDC settings are missing. '
            'Set OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET, plus either '
            'OIDC_OP_DISCOVERY_ENDPOINT or all explicit endpoints '
            '(OIDC_OP_AUTHORIZATION_ENDPOINT, OIDC_OP_TOKEN_ENDPOINT, '
            'OIDC_OP_USER_ENDPOINT, OIDC_OP_JWKS_ENDPOINT).'
        )

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Logging — pilot warning events go to logs/pilot.log so scripts/pilot_log_summary.py
# can parse them. All loggers also emit to the console (default Django behaviour).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'pilot_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'pilot.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'contracts.views': {
            'handlers': ['console', 'pilot_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
