"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _bool_env(name: str, default: bool = False) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


def _csv_env(name: str, default: list[str] | None = None) -> list[str]:
    raw = os.getenv(name)
    if raw is None:
        return list(default or [])
    return [item.strip() for item in raw.split(',') if item.strip()]


def _invalid_database_url(message: str) -> ImproperlyConfigured:
    return ImproperlyConfigured(
        f"{message} Expected format: "
        "postgresql://USER:PASSWORD@HOST:5432/DBNAME?sslmode=require"
    )


def _looks_like_placeholder_database_url(database_url: str) -> bool:
    """
    Treat obvious template or placeholder DATABASE_URL values as "unset".

    This keeps local development usable when .env contains a copied production
    connection string skeleton such as INSERT_YOUR_SUPABASE_DB_PASSWORD.
    """
    lowered = database_url.strip().lower()
    return any(
        marker in lowered
        for marker in (
            'insert_your_',
            'your_db_host',
            'your_password',
            'change_me',
            'placeholder',
        )
    )


def _database_config() -> dict[str, object]:
    database_url = os.getenv('DATABASE_URL', '').strip()
    if not database_url or _looks_like_placeholder_database_url(database_url):
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed = urlparse(database_url)
    scheme = parsed.scheme.lower()

    if scheme in {'postgres', 'postgresql'}:
        query = parse_qs(parsed.query)
        try:
            port = parsed.port
        except ValueError as exc:
            raise _invalid_database_url(
                'DATABASE_URL has an invalid port value. Do not use placeholder text like "port".'
            ) from exc

        database_name = parsed.path.lstrip('/')
        if not parsed.hostname or not database_name:
            raise _invalid_database_url(
                'DATABASE_URL is missing a hostname or database name.'
            )

        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': database_name,
            'USER': parsed.username or '',
            'PASSWORD': parsed.password or '',
            'HOST': parsed.hostname or '',
            'PORT': str(port or '5432'),
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '600')),
            'OPTIONS': {
                'sslmode': query.get('sslmode', ['require'])[0],
            },
        }

    if scheme == 'sqlite':
        sqlite_target = database_url[len('sqlite:///'):]
        if database_url.startswith('sqlite:////'):
            sqlite_path = Path('/') / sqlite_target.lstrip('/')
        else:
            sqlite_path = BASE_DIR / sqlite_target.lstrip('/') if sqlite_target else BASE_DIR / 'db.sqlite3'
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': sqlite_path,
        }

    raise _invalid_database_url(
        f'DATABASE_URL uses unsupported scheme {parsed.scheme!r}. Use postgresql:// or postgres://.'
    )


def _load_dotenv(dotenv_path: Path) -> None:
    if not dotenv_path.exists():
        return
    for raw_line in dotenv_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    os.getenv('SECRET_KEY', 'django-insecure-h4dao*+381s=dgr2v6+1!#%ui6bz4#f95*hfcq!m73vn!^#)u&'),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _bool_env('DJANGO_DEBUG', default=_bool_env('DEBUG', default=False))
ENABLE_DJANGO_BROWSER_RELOAD = _bool_env('ENABLE_DJANGO_BROWSER_RELOAD', default=False)

ALLOWED_HOSTS = _csv_env('ALLOWED_HOSTS', default=['*'])
if '*' not in ALLOWED_HOSTS:
    _LOCAL_ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, *_LOCAL_ALLOWED_HOSTS]))

# Render injects RENDER_EXTERNAL_HOSTNAME / RENDER_EXTERNAL_URL for every service
# (e.g. "carelane-web-630u.onrender.com"). Auto-trust them so recreating the service
# — which changes the hostname — never 400s on a stale ALLOWED_HOSTS / CSRF list,
# and so SPA_ORIGIN / OIDC redirect resolve to the live host without manual env
# edits. No effect locally or in tests (the vars are unset).
_RENDER_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
_RENDER_URL = os.getenv('RENDER_EXTERNAL_URL', '').strip().rstrip('/')
if _RENDER_HOSTNAME and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS = list(dict.fromkeys([*ALLOWED_HOSTS, _RENDER_HOSTNAME]))

_LOCAL_CSRF_ORIGINS = [
    'http://localhost:3000',
    'https://localhost:3000',
    'http://localhost:5173',
    'https://localhost:5173',
    'http://127.0.0.1:3000',
    'https://127.0.0.1:3000',
    'http://127.0.0.1:5173',
    'https://127.0.0.1:5173',
    'http://[::1]:3000',
    'https://[::1]:3000',
    'http://[::1]:5173',
    'https://[::1]:5173',
    # Vite proxy may forward with Django as Host; allow same-origin checks when needed.
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',
    'http://localhost:8000',
    'https://localhost:8000',
    'https://*.replit.dev',
    'https://*.repl.co',
    'https://*.riker.replit.dev',
    'https://*.riker.replit.dev:8000',
]
_csrf_from_env = _csv_env('CSRF_TRUSTED_ORIGINS', default=_LOCAL_CSRF_ORIGINS)
# Always keep local Vite/Django origins for developer workflows; production
# settings remove loopback entries explicitly after importing this module.
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(_csrf_from_env + _LOCAL_CSRF_ORIGINS))
if _RENDER_HOSTNAME:
    _render_origin = _RENDER_URL or f'https://{_RENDER_HOSTNAME}'
    CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([*CSRF_TRUSTED_ORIGINS, _render_origin]))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'theme',
    'contracts',
]

if DEBUG and ENABLE_DJANGO_BROWSER_RELOAD:
    INSTALLED_APPS.extend([
        'django_browser_reload',
        'debug_toolbar',
    ])


SSO_ENABLED = _bool_env('SSO_ENABLED', default=False)

try:
    import mozilla_django_oidc  # noqa: F401
    OIDC_PACKAGE_AVAILABLE = True
except Exception:
    OIDC_PACKAGE_AVAILABLE = False

if OIDC_PACKAGE_AVAILABLE:
    INSTALLED_APPS.append('mozilla_django_oidc')

if SSO_ENABLED and not OIDC_PACKAGE_AVAILABLE:
    raise ImportError(
        'SSO_ENABLED is true but mozilla-django-oidc is not installed. '
        'Install it with: pip install mozilla-django-oidc'
    )

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'contracts.middleware.OperationalObservabilityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'contracts.oidc_middleware.OIDCCanonicalPublicUrlMiddleware',
    'contracts.middleware.ApiVersioningMiddleware',
    'contracts.middleware.OrganizationMiddleware',
    'contracts.middleware.SpaShellMigrationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG and ENABLE_DJANGO_BROWSER_RELOAD:
    MIDDLEWARE.insert(2, 'debug_toolbar.middleware.DebugToolbarMiddleware')
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'theme/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'contracts.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': _database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'nl'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

def _build_cache_config():
    redis_url = os.getenv('REDIS_URL', '').strip()
    if redis_url:
        return {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': redis_url,
                'OPTIONS': {
                    'socket_connect_timeout': 5,
                    'socket_timeout': 5,
                },
            }
        }
    return {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


CACHES = _build_cache_config()

# DB-level tenant isolation backstop (manager default-scope during requests).
TENANT_DB_BACKSTOP_ENABLED = _bool_env('TENANT_DB_BACKSTOP_ENABLED', default=True)

# Login brute-force protection (requires shared cache in multi-worker production).
AUTH_LOGIN_RATE_LIMIT_ENABLED = _bool_env('AUTH_LOGIN_RATE_LIMIT_ENABLED', default=True)
AUTH_LOGIN_MAX_ATTEMPTS = int(os.getenv('AUTH_LOGIN_MAX_ATTEMPTS', '5'))
AUTH_LOGIN_ATTEMPT_WINDOW_SECONDS = int(os.getenv('AUTH_LOGIN_ATTEMPT_WINDOW_SECONDS', '900'))
AUTH_LOGIN_LOCKOUT_SECONDS = int(os.getenv('AUTH_LOGIN_LOCKOUT_SECONDS', '900'))

# Audit trail read/export window (days). 0 = no retention filter. Default ~7 years (gemeente compliance).
CARELANE_AUDIT_LOG_RETENTION_DAYS = int(os.getenv('CARELANE_AUDIT_LOG_RETENTION_DAYS', '2555'))

# When true, signup and auto-org provisioning require a pending OrganizationInvitation.
CARELANE_INVITE_ONLY_ONBOARDING = _bool_env('CARELANE_INVITE_ONLY_ONBOARDING', default=False)

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# `theme` is an installed app, so its `static/` directory is already
# discovered by Django's AppDirectoriesFinder. Keeping it in STATICFILES_DIRS
# would duplicate every file during collectstatic.
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Feature Flags
# Pilot: server-driven UI (hide demo role switch) and optional single SPA workflow rail
CARELANE_PILOT_UI = _bool_env('CARELANE_PILOT_UI', False)
CARELANE_PILOT_SPA_ONLY = _bool_env('CARELANE_PILOT_SPA_ONLY', False)
# Upload: maximum document size accepted by the API (in megabytes)
CARELANE_MAX_DOCUMENT_UPLOAD_MB = int(os.getenv('CARELANE_MAX_DOCUMENT_UPLOAD_MB', '20'))

# ── SLA thresholds (hours) ────────────────────────────────────────────────────
# Override these via Render env vars.  They are also the default fallback when no
# SystemPolicyConfig DB row exists (contracts.governance.get_policy_values()).
# decision_engine.py thresholds — provider SLA countdown and matching urgency:
CARELANE_SLA_AANMELDING_HOURS = int(os.getenv('CARELANE_SLA_AANMELDING_HOURS', '24'))
CARELANE_SLA_PROVIDER_RESPONSE_HOURS = int(os.getenv('CARELANE_SLA_PROVIDER_RESPONSE_HOURS', '72'))
CARELANE_SLA_URGENT_IDLE_HOURS = int(os.getenv('CARELANE_SLA_URGENT_IDLE_HOURS', '48'))
CARELANE_SLA_INTAKE_START_DAYS = int(os.getenv('CARELANE_SLA_INTAKE_START_DAYS', '5'))
CARELANE_SLA_REPEATED_REJECTION_COUNT = int(os.getenv('CARELANE_SLA_REPEATED_REJECTION_COUNT', '2'))
# case_intelligence.py thresholds — provider-response SLA escalation ladder:
CARELANE_SLA_PENDING_ON_TRACK_HOURS = int(os.getenv('CARELANE_SLA_PENDING_ON_TRACK_HOURS', '48'))
CARELANE_SLA_PENDING_AT_RISK_HOURS = int(os.getenv('CARELANE_SLA_PENDING_AT_RISK_HOURS', '72'))
CARELANE_SLA_PENDING_OVERDUE_HOURS = int(os.getenv('CARELANE_SLA_PENDING_OVERDUE_HOURS', '96'))
CARELANE_SLA_PENDING_ESCALATED_HOURS = int(os.getenv('CARELANE_SLA_PENDING_ESCALATED_HOURS', '120'))
CARELANE_SLA_NEEDS_INFO_ON_TRACK_HOURS = int(os.getenv('CARELANE_SLA_NEEDS_INFO_ON_TRACK_HOURS', '24'))
CARELANE_SLA_NEEDS_INFO_AT_RISK_HOURS = int(os.getenv('CARELANE_SLA_NEEDS_INFO_AT_RISK_HOURS', '48'))
CARELANE_SLA_NEEDS_INFO_OVERDUE_HOURS = int(os.getenv('CARELANE_SLA_NEEDS_INFO_OVERDUE_HOURS', '72'))
CARELANE_SLA_WAITLIST_ESCALATED_HOURS = int(os.getenv('CARELANE_SLA_WAITLIST_ESCALATED_HOURS', '72'))

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGIN_REDIRECT_URL_FAILURE = '/login/?sso_error=1'
LOGOUT_REDIRECT_URL = '/'
# Treat an empty SPA_ORIGIN (e.g. a blank Render env var) the same as unset, so
# it falls back to the live Render URL instead of an empty/broken origin.
SPA_ORIGIN = (os.getenv('SPA_ORIGIN', '').strip() or _RENDER_URL or 'http://127.0.0.1:3000').rstrip('/')


def _resolve_oidc_public_base_url() -> str:
    """Canonical origin for OAuth redirect_uri (must match Google authorized redirect URIs)."""
    explicit = os.getenv('OIDC_PUBLIC_BASE_URL', '').strip().rstrip('/')
    if explicit:
        return explicit
    # Prefer Render's own external URL so the OAuth redirect always targets the
    # live service host after a recreate — no manual env edit needed. (You still
    # must add this origin to Google's authorized redirect URIs.)
    if _RENDER_URL:
        return _RENDER_URL
    for origin in CSRF_TRUSTED_ORIGINS:
        candidate = (origin or '').strip().rstrip('/')
        if not candidate.startswith('https://'):
            continue
        if 'localhost' in candidate or '127.0.0.1' in candidate:
            continue
        return candidate
    return 'http://127.0.0.1:8000'


OIDC_PUBLIC_BASE_URL = _resolve_oidc_public_base_url()
OIDC_REDIRECT_ALLOWED_HOSTS = [
    host
    for host in _csv_env(
        'OIDC_REDIRECT_ALLOWED_HOSTS',
        default=[
            urlparse(SPA_ORIGIN).netloc,
            'localhost:3000',
            '127.0.0.1:3000',
        ],
    )
    if host
]
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@carelane.nl')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _bool_env('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# Auto-promote to SMTP when EMAIL_HOST is set; fall back to console for local dev.
_smtp_configured = bool(EMAIL_HOST)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if _smtp_configured
    else 'django.core.mail.backends.console.EmailBackend',
)

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if SSO_ENABLED:
    AUTHENTICATION_BACKENDS.insert(0, 'contracts.auth_backends.CarelaneOIDCAuthenticationBackend')
    OIDC_CALLBACK_CLASS = 'contracts.auth_backends.CarelaneOIDCCallbackView'

OIDC_RP_CLIENT_ID = os.getenv('OIDC_RP_CLIENT_ID', '')
OIDC_RP_CLIENT_SECRET = os.getenv('OIDC_RP_CLIENT_SECRET', '')
OIDC_RP_SIGN_ALGO = os.getenv('OIDC_RP_SIGN_ALGO', 'RS256')
# Keep as a space-delimited string to match mozilla-django-oidc expectations.
OIDC_RP_SCOPES = os.getenv('OIDC_RP_SCOPES', 'openid email profile')
SSO_ALLOWED_EMAIL_DOMAINS = [
    d.strip().lower()
    for d in os.getenv('SSO_ALLOWED_EMAIL_DOMAINS', '').split(',')
    if d.strip()
]

OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_OP_AUTHORIZATION_ENDPOINT', '')
OIDC_OP_TOKEN_ENDPOINT = os.getenv('OIDC_OP_TOKEN_ENDPOINT', '')
OIDC_OP_USER_ENDPOINT = os.getenv('OIDC_OP_USER_ENDPOINT', '')
OIDC_OP_JWKS_ENDPOINT = os.getenv('OIDC_OP_JWKS_ENDPOINT', '')
OIDC_OP_LOGOUT_ENDPOINT = os.getenv('OIDC_OP_LOGOUT_ENDPOINT', '')
OIDC_OP_DISCOVERY_ENDPOINT = os.getenv('OIDC_OP_DISCOVERY_ENDPOINT', '')

OIDC_USE_NONCE = True
OIDC_STORE_ACCESS_TOKEN = False
OIDC_VERIFY_SSL = _bool_env('OIDC_VERIFY_SSL', default=True)

if SSO_ENABLED:
    has_discovery = bool(OIDC_OP_DISCOVERY_ENDPOINT)
    has_explicit_endpoints = all([
        OIDC_OP_AUTHORIZATION_ENDPOINT,
        OIDC_OP_TOKEN_ENDPOINT,
        OIDC_OP_USER_ENDPOINT,
        OIDC_OP_JWKS_ENDPOINT,
    ])

    if not (OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET and (has_discovery or has_explicit_endpoints)):
        raise ImportError(
            'SSO_ENABLED is true but required OIDC settings are missing. '
            'Set OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET, plus either '
            'OIDC_OP_DISCOVERY_ENDPOINT or all explicit endpoints '
            '(OIDC_OP_AUTHORIZATION_ENDPOINT, OIDC_OP_TOKEN_ENDPOINT, '
            'OIDC_OP_USER_ENDPOINT, OIDC_OP_JWKS_ENDPOINT).'
        )

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Authenticated media serving. When True, download views emit X-Accel-Redirect and rely on nginx:
#   location /protected_media/ { internal; alias /path/to/media/; }
NGINX_MEDIA_ACCEL_REDIRECT = _bool_env('NGINX_MEDIA_ACCEL_REDIRECT', default=False)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True

QUIET_TEST_LOGS = os.getenv('DJANGO_TEST_LOG_LEVEL', '').strip().upper()
if not QUIET_TEST_LOGS and any(arg == 'test' for arg in sys.argv):
    QUIET_TEST_LOGS = 'ERROR'

# Log every successful /care/api/* request at INFO (verbose); default is 4xx/5xx only via middleware.
CARELANE_API_ACCESS_LOG_ALL = _bool_env('CARELANE_API_ACCESS_LOG_ALL', default=False)

# Geocoding / maps (optional — PDOK is default for backend geocoding)
GOOGLE_GEOCODING_API_KEY = os.getenv('GOOGLE_GEOCODING_API_KEY', '').strip()
GEOCODING_PREFER_GOOGLE = _bool_env('GEOCODING_PREFER_GOOGLE', default=False)

# Infrastructure maturity feature freeze (see docs/INFRASTRUCTURE_MATURITY_PHASE.md).
FEATURE_FREEZE_ACTIVE = _bool_env('FEATURE_FREEZE_ACTIVE', default=True)

# Logging — pilot warning events go to logs/pilot.log so scripts/pilot_log_summary.py
# can parse them. All loggers also emit to the console (default Django behaviour).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'correlation_id': {
            '()': 'contracts.observability.CorrelationIdFilter',
        },
    },
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} corr={correlation_id} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
            'filters': ['correlation_id'],
        },
        'pilot_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'pilot.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'standard',
            'filters': ['correlation_id'],
        },
    },
    'loggers': {
        'contracts.views': {
            'handlers': ['console', 'pilot_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'contracts.api.views': {
            'handlers': ['console', 'pilot_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'contracts.observability': {
            'handlers': ['console', 'pilot_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

if QUIET_TEST_LOGS in {'ERROR', 'CRITICAL'}:
    LOGGING['root']['level'] = QUIET_TEST_LOGS
    for logger_name in (
        'django.request',
        'contracts.views',
        'contracts.api.views',
        'contracts.observability',
        'contracts.decision_quality',
        'contracts.governance',
        'contracts.provider_pipeline',
    ):
        logger_config = LOGGING['loggers'].setdefault(logger_name, {})
        logger_config['level'] = QUIET_TEST_LOGS
