"""Zorg OS V3 Decision Intelligence Observability Module.

Purpose
-------
Measures whether the confidence signals, rejection taxonomy, and decision
guidance generated by the V3 case-intelligence layer are actually predictive
and useful in real operation.

Design rules
------------
- Pure read-only analytics layer.  No side effects, no writes.
- All functions return structured dicts and are safe when data is incomplete.
- Scoped to an ``Organization`` to maintain tenant isolation.
- Each builder is independently usable; callers may combine them.
- No business logic, no recommendations, no scoring — only observed metrics.

Public API
----------
build_confidence_calibration_report(org)       -> Dict
build_rejection_taxonomy_report(org)           -> Dict
build_repeated_rejection_report(org)           -> Dict
build_weak_match_false_positive_report(org)    -> Dict
build_override_tracking_report(org)            -> Dict
build_full_observability_report(org)           -> Dict   (combines all five)
"""

from __future__ import annotations

import logging
from collections import Counter, defaultdict
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Empty / safe defaults
# ---------------------------------------------------------------------------

def _empty_calibration() -> Dict[str, Any]:
    return {
        "buckets": [],
        "total_cases_analysed": 0,
        "data_available": False,
        "note": "Insufficient data",
    }


def _empty_taxonomy() -> Dict[str, Any]:
    return {
        "by_provider": [],
        "by_care_category": [],
        "overall_distribution": [],
        "total_rejections": 0,
        "data_available": False,
    }


def _empty_repeated_rejection() -> Dict[str, Any]:
    return {
        "cases_with_repeated_rejections": [],
        "providers_with_repeated_same_reason": [],
        "total_bouncing_cases": 0,
        "data_available": False,
    }


def _empty_false_positive() -> Dict[str, Any]:
    return {
        "total_weak_match_alerts": 0,
        "accepted_after_weak_match": 0,
        "false_positive_rate": None,
        "total_no_weak_match_alert": 0,
        "accepted_without_weak_match_alert": 0,
        "data_available": False,
        "note": "Insufficient data",
    }


def _empty_override_tracking() -> Dict[str, Any]:
    return {
        "total_overrides": 0,
        "by_override_type": [],
        "by_primary_reason": [],
        "override_rate": None,
        "data_available": False,
    }


# ---------------------------------------------------------------------------
# Confidence calibration report
# ---------------------------------------------------------------------------


def build_confidence_calibration_report(organization: Any) -> Dict[str, Any]:
    """Compare predicted confidence level against actual provider outcomes.

    Predicted confidence is proxied from the ``OperationalAlert`` record with
    type ``WEAK_MATCH_NEEDS_REVIEW``.  Cases that ever triggered this alert are
    treated as "predicted low/weak confidence"; all other cases as
    "predicted medium/high confidence".

    For each bucket the report shows:
    - provider acceptance rate
    - placement success rate (PlacementRequest.Status.APPROVED)
    - intake completion rate (IntakeOutcomeStatus.COMPLETED)
    - count of cases in bucket

    Returns
    -------
    dict with ``buckets`` list, counts, and ``data_available`` flag.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_calibration()

    try:
        return _compute_confidence_calibration(organization)
    except Exception:
        logger.exception("build_confidence_calibration_report failed for org %s", getattr(organization, "pk", None))
        return _empty_calibration()


def _compute_confidence_calibration(organization: Any) -> Dict[str, Any]:
    from contracts.models import CaseIntakeProcess, OperationalAlert, PlacementRequest, ProviderEvaluation

    # All cases for this org.
    case_ids = list(
        CaseIntakeProcess.objects.filter(organization=organization).values_list("pk", flat=True)
    )
    if not case_ids:
        return _empty_calibration()

    # Cases that triggered a WEAK_MATCH alert (ever).
    weak_match_case_ids = set(
        OperationalAlert.objects.filter(
            case_id__in=case_ids,
            alert_type=OperationalAlert.AlertType.WEAK_MATCH_NEEDS_REVIEW,
        ).values_list("case_id", flat=True).distinct()
    )

    all_case_id_set = set(case_ids)
    strong_case_ids = all_case_id_set - weak_match_case_ids

    buckets = []
    for label, confidence_label, bucket_case_ids in [
        ("Zwakke match (WEAK_MATCH alert)", "low", weak_match_case_ids),
        ("Sterke/gemiddelde match (geen WEAK_MATCH alert)", "high_medium", strong_case_ids),
    ]:
        if not bucket_case_ids:
            continue

        bucket_list = list(bucket_case_ids)

        # Provider acceptance: at least one ProviderEvaluation.ACCEPT per case.
        accepted_case_ids = set(
            ProviderEvaluation.objects.filter(
                case_id__in=bucket_list,
                decision="accept",
            ).values_list("case_id", flat=True).distinct()
        )

        # Placement success: at least one PlacementRequest with status APPROVED.
        placement_success_ids = set(
            PlacementRequest.objects.filter(
                due_diligence_process_id__in=bucket_list,
                status=PlacementRequest.Status.APPROVED,
            ).values_list("due_diligence_process_id", flat=True).distinct()
        )

        # Intake completion.
        intake_complete_ids = set(
            CaseIntakeProcess.objects.filter(
                pk__in=bucket_list,
                intake_outcome_status=CaseIntakeProcess.IntakeOutcomeStatus.COMPLETED,
            ).values_list("pk", flat=True)
        )

        total = len(bucket_list)
        buckets.append({
            "label": label,
            "confidence_proxy": confidence_label,
            "total_cases": total,
            "provider_acceptance_count": len(accepted_case_ids),
            "provider_acceptance_rate": round(len(accepted_case_ids) / total, 4) if total else None,
            "placement_success_count": len(placement_success_ids),
            "placement_success_rate": round(len(placement_success_ids) / total, 4) if total else None,
            "intake_completion_count": len(intake_complete_ids),
            "intake_completion_rate": round(len(intake_complete_ids) / total, 4) if total else None,
        })

    return {
        "buckets": buckets,
        "total_cases_analysed": len(case_ids),
        "total_weak_match_cases": len(weak_match_case_ids),
        "data_available": bool(buckets),
        "note": (
            "Confidence proxy: WEAK_MATCH_NEEDS_REVIEW alert presence. "
            "Strong/medium = no weak-match alert raised."
        ),
    }


# ---------------------------------------------------------------------------
# Rejection taxonomy report
# ---------------------------------------------------------------------------


def build_rejection_taxonomy_report(organization: Any) -> Dict[str, Any]:
    """Aggregate rejection reason distribution by provider and care category.

    Returns
    -------
    dict with ``by_provider``, ``by_care_category``, and
    ``overall_distribution`` lists.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_taxonomy()

    try:
        return _compute_rejection_taxonomy(organization)
    except Exception:
        logger.exception("build_rejection_taxonomy_report failed for org %s", getattr(organization, "pk", None))
        return _empty_taxonomy()


def _compute_rejection_taxonomy(organization: Any) -> Dict[str, Any]:
    from contracts.models import ProviderEvaluation

    rows = list(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            decision="reject",
        ).select_related("provider", "case__care_category_main").values(
            "reason_code",
            "provider_id",
            "provider__name",
            "case__care_category_main_id",
            "case__care_category_main__name",
        )
    )

    if not rows:
        return _empty_taxonomy()

    # Overall distribution.
    overall_counter: Counter = Counter(r["reason_code"] for r in rows)
    overall_distribution = [
        {"reason_code": code, "count": count, "share": round(count / len(rows), 4)}
        for code, count in overall_counter.most_common()
    ]

    # By provider.
    provider_reason_counts: Dict[Any, Counter] = defaultdict(Counter)
    provider_names: Dict[Any, str] = {}
    for r in rows:
        pid = r["provider_id"]
        provider_reason_counts[pid][r["reason_code"]] += 1
        provider_names[pid] = r["provider__name"] or f"Provider {pid}"

    by_provider = []
    for pid, counter in provider_reason_counts.items():
        total_rejections = sum(counter.values())
        top_reason = counter.most_common(1)[0][0] if counter else None
        by_provider.append({
            "provider_id": pid,
            "provider_name": provider_names.get(pid, f"Provider {pid}"),
            "total_rejections": total_rejections,
            "top_reason_code": top_reason,
            "reason_breakdown": [
                {"reason_code": code, "count": cnt, "share": round(cnt / total_rejections, 4)}
                for code, cnt in counter.most_common()
            ],
        })
    by_provider.sort(key=lambda x: x["total_rejections"], reverse=True)

    # By care category.
    category_reason_counts: Dict[Any, Counter] = defaultdict(Counter)
    category_names: Dict[Any, str] = {}
    for r in rows:
        cid = r["case__care_category_main_id"]
        if cid is None:
            cid = "__unknown__"
        category_reason_counts[cid][r["reason_code"]] += 1
        category_names[cid] = r["case__care_category_main__name"] or "Onbekende categorie"

    by_care_category = []
    for cid, counter in category_reason_counts.items():
        total = sum(counter.values())
        by_care_category.append({
            "care_category_id": cid if cid != "__unknown__" else None,
            "care_category_name": category_names.get(cid, "Onbekende categorie"),
            "total_rejections": total,
            "reason_breakdown": [
                {"reason_code": code, "count": cnt, "share": round(cnt / total, 4)}
                for code, cnt in counter.most_common()
            ],
        })
    by_care_category.sort(key=lambda x: x["total_rejections"], reverse=True)

    return {
        "by_provider": by_provider,
        "by_care_category": by_care_category,
        "overall_distribution": overall_distribution,
        "total_rejections": len(rows),
        "data_available": True,
    }


# ---------------------------------------------------------------------------
# Repeated rejection report
# ---------------------------------------------------------------------------


def build_repeated_rejection_report(organization: Any) -> Dict[str, Any]:
    """Identify cases with repeated rejections and providers with patterns.

    A case is flagged when it has >= 2 rejection evaluations.
    A provider is flagged when it has >= 3 rejections of the same reason code.

    Returns
    -------
    dict with ``cases_with_repeated_rejections``,
    ``providers_with_repeated_same_reason``, and summary counts.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_repeated_rejection()

    try:
        return _compute_repeated_rejections(organization)
    except Exception:
        logger.exception("build_repeated_rejection_report failed for org %s", getattr(organization, "pk", None))
        return _empty_repeated_rejection()


def _compute_repeated_rejections(organization: Any) -> Dict[str, Any]:
    from contracts.models import ProviderEvaluation

    rejection_rows = list(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            decision="reject",
        ).select_related("case").values(
            "case_id",
            "case__title",
            "provider_id",
            "provider__name",
            "reason_code",
            "created_at",
        )
    )

    if not rejection_rows:
        return _empty_repeated_rejection()

    # Bouncing cases: cases with >= 2 rejection records.
    case_rejection_count: Counter = Counter(r["case_id"] for r in rejection_rows)
    case_titles: Dict[Any, str] = {r["case_id"]: r["case__title"] or f"Casus {r['case_id']}" for r in rejection_rows}

    cases_with_repeated = []
    for case_id, count in case_rejection_count.items():
        if count >= 2:
            case_rows = [r for r in rejection_rows if r["case_id"] == case_id]
            providers_involved = list({r["provider_id"] for r in case_rows})
            reason_codes = [r["reason_code"] for r in case_rows]
            cases_with_repeated.append({
                "case_id": case_id,
                "case_title": case_titles.get(case_id, f"Casus {case_id}"),
                "total_rejections": count,
                "providers_involved": len(providers_involved),
                "reason_distribution": dict(Counter(reason_codes).most_common()),
            })
    cases_with_repeated.sort(key=lambda x: x["total_rejections"], reverse=True)

    # Providers with repeated same reason (>= 3 of the same code).
    provider_reason_counter: Dict[tuple, int] = Counter(
        (r["provider_id"], r["reason_code"]) for r in rejection_rows
    )
    provider_names: Dict[Any, str] = {r["provider_id"]: r["provider__name"] or f"Provider {r['provider_id']}" for r in rejection_rows}

    providers_with_pattern = []
    seen_providers: set = set()
    for (pid, reason_code), count in provider_reason_counter.most_common():
        if count >= 3:
            providers_with_pattern.append({
                "provider_id": pid,
                "provider_name": provider_names.get(pid, f"Provider {pid}"),
                "repeated_reason_code": reason_code,
                "repeat_count": count,
            })
            seen_providers.add(pid)

    return {
        "cases_with_repeated_rejections": cases_with_repeated,
        "providers_with_repeated_same_reason": providers_with_pattern,
        "total_bouncing_cases": len(cases_with_repeated),
        "total_providers_with_pattern": len(seen_providers),
        "data_available": bool(cases_with_repeated or providers_with_pattern),
    }


# ---------------------------------------------------------------------------
# Weak-match false positive rate report
# ---------------------------------------------------------------------------


def build_weak_match_false_positive_report(organization: Any) -> Dict[str, Any]:
    """Measure the false positive rate of the WEAK_MATCH_NEEDS_REVIEW alert.

    A false positive is defined as: the WEAK_MATCH alert was raised for a case,
    but the provider eventually accepted (i.e., the alert was needlessly alarming).

    Also reports the true positive rate (alert raised, provider eventually rejected).

    Returns
    -------
    dict with raw counts, false_positive_rate, and true_positive_rate.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_false_positive()

    try:
        return _compute_weak_match_false_positive(organization)
    except Exception:
        logger.exception("build_weak_match_false_positive_report failed for org %s", getattr(organization, "pk", None))
        return _empty_false_positive()


def _compute_weak_match_false_positive(organization: Any) -> Dict[str, Any]:
    from contracts.models import CaseIntakeProcess, OperationalAlert, ProviderEvaluation

    case_ids = list(
        CaseIntakeProcess.objects.filter(organization=organization).values_list("pk", flat=True)
    )
    if not case_ids:
        return _empty_false_positive()

    # Cases that ever had a WEAK_MATCH alert.
    weak_match_case_ids = set(
        OperationalAlert.objects.filter(
            case_id__in=case_ids,
            alert_type=OperationalAlert.AlertType.WEAK_MATCH_NEEDS_REVIEW,
        ).values_list("case_id", flat=True).distinct()
    )

    # Cases without a WEAK_MATCH alert.
    no_weak_match_ids = set(case_ids) - weak_match_case_ids

    # Among WEAK_MATCH cases: how many got accepted?
    accepted_after_weak = set(
        ProviderEvaluation.objects.filter(
            case_id__in=list(weak_match_case_ids),
            decision="accept",
        ).values_list("case_id", flat=True).distinct()
    ) if weak_match_case_ids else set()

    # Among NO-WEAK_MATCH cases: how many got accepted?
    accepted_without_weak = set(
        ProviderEvaluation.objects.filter(
            case_id__in=list(no_weak_match_ids),
            decision="accept",
        ).values_list("case_id", flat=True).distinct()
    ) if no_weak_match_ids else set()

    total_weak = len(weak_match_case_ids)
    total_no_weak = len(no_weak_match_ids)
    accepted_weak = len(accepted_after_weak)
    accepted_no_weak = len(accepted_without_weak)

    false_positive_rate: Optional[float] = None
    true_positive_rate: Optional[float] = None
    if total_weak > 0:
        # FP: alert fired but case was accepted anyway.
        false_positive_rate = round(accepted_weak / total_weak, 4)
        # TP: alert fired and case was NOT accepted (rejected/no response).
        rejected_weak = total_weak - accepted_weak
        true_positive_rate = round(rejected_weak / total_weak, 4)

    # Acceptance rate for non-alerted cases (baseline comparison).
    baseline_acceptance_rate: Optional[float] = None
    if total_no_weak > 0:
        baseline_acceptance_rate = round(accepted_no_weak / total_no_weak, 4)

    return {
        "total_weak_match_alerts": total_weak,
        "accepted_after_weak_match": accepted_weak,
        "rejected_after_weak_match": total_weak - accepted_weak if total_weak else 0,
        "false_positive_rate": false_positive_rate,
        "true_positive_rate": true_positive_rate,
        "total_no_weak_match_alert": total_no_weak,
        "accepted_without_weak_match_alert": accepted_no_weak,
        "baseline_acceptance_rate": baseline_acceptance_rate,
        "data_available": total_weak > 0,
        "note": (
            "False positive: WEAK_MATCH alert fired but provider eventually accepted. "
            "True positive: alert fired and case remained rejected/unaccepted."
        ),
    }


# ---------------------------------------------------------------------------
# Operator override tracking report
# ---------------------------------------------------------------------------


def build_override_tracking_report(organization: Any) -> Dict[str, Any]:
    """Report on operator overrides recorded via DecisionQualityReview.

    Returns
    -------
    dict with total override count, by_override_type, by_primary_reason,
    and the override rate as a fraction of all reviews.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_override_tracking()

    try:
        return _compute_override_tracking(organization)
    except Exception:
        logger.exception("build_override_tracking_report failed for org %s", getattr(organization, "pk", None))
        return _empty_override_tracking()


def _compute_override_tracking(organization: Any) -> Dict[str, Any]:
    from contracts.models import DecisionQualityReview

    all_reviews = list(
        DecisionQualityReview.objects.filter(
            case__organization=organization,
        ).values(
            "override_present",
            "override_type",
            "primary_reason",
            "decision_quality",
        )
    )

    if not all_reviews:
        return _empty_override_tracking()

    total_reviews = len(all_reviews)
    overrides = [r for r in all_reviews if r["override_present"]]
    total_overrides = len(overrides)

    by_override_type_counter: Counter = Counter(
        r["override_type"] or "unspecified" for r in overrides
    )
    by_override_type = [
        {"override_type": ot, "count": cnt, "share": round(cnt / total_overrides, 4) if total_overrides else 0}
        for ot, cnt in by_override_type_counter.most_common()
    ]

    by_reason_counter: Counter = Counter(r["primary_reason"] for r in overrides)
    by_primary_reason = [
        {"primary_reason": reason, "count": cnt, "share": round(cnt / total_overrides, 4) if total_overrides else 0}
        for reason, cnt in by_reason_counter.most_common()
    ]

    # Decision quality when override was present.
    override_quality_counter: Counter = Counter(r["decision_quality"] for r in overrides)
    override_quality_distribution = [
        {"decision_quality": dq, "count": cnt}
        for dq, cnt in override_quality_counter.most_common()
    ]

    override_rate = round(total_overrides / total_reviews, 4) if total_reviews else None

    return {
        "total_reviews": total_reviews,
        "total_overrides": total_overrides,
        "by_override_type": by_override_type,
        "by_primary_reason": by_primary_reason,
        "override_quality_distribution": override_quality_distribution,
        "override_rate": override_rate,
        "data_available": total_reviews > 0,
    }


# ---------------------------------------------------------------------------
# Combined report
# ---------------------------------------------------------------------------


def build_full_observability_report(organization: Any) -> Dict[str, Any]:
    """Combine all five observability reports into a single dict.

    Safe when any sub-report fails — each is independently guarded.
    """
    return {
        "confidence_calibration": build_confidence_calibration_report(organization),
        "rejection_taxonomy": build_rejection_taxonomy_report(organization),
        "repeated_rejections": build_repeated_rejection_report(organization),
        "weak_match_false_positive": build_weak_match_false_positive_report(organization),
        "override_tracking": build_override_tracking_report(organization),
    }
