"""Zorg OS V3 Decision Intelligence Observability Module.

Purpose
-------
Measures whether the confidence signals, rejection taxonomy, and decision
guidance generated by the V3 case-intelligence layer are actually predictive
and useful in real operation.

Design rules
------------
- Pure read-only analytics layer.  No side effects, no writes.
- All functions return structured dicts and are safe when data is incomplete.
- Scoped to an ``Organization`` to maintain tenant isolation.
- Each builder is independently usable; callers may combine them.
- No business logic, no recommendations, no scoring — only observed metrics.

Public API
----------
build_confidence_calibration_report(org)       -> Dict
build_rejection_taxonomy_report(org)           -> Dict
build_repeated_rejection_report(org)           -> Dict
build_weak_match_false_positive_report(org)    -> Dict
build_override_tracking_report(org)            -> Dict
build_full_observability_report(org)           -> Dict   (combines all five)
"""

from __future__ import annotations

import logging
from collections import Counter, defaultdict
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Empty / safe defaults
# ---------------------------------------------------------------------------

def _empty_calibration() -> Dict[str, Any]:
    return {
        "buckets": [],
        "total_cases_analysed": 0,
        "data_available": False,
        "note": "Insufficient data",
    }


def _empty_taxonomy() -> Dict[str, Any]:
    return {
        "by_provider": [],
        "by_care_category": [],
        "overall_distribution": [],
        "total_rejections": 0,
        "data_available": False,
    }


def _empty_repeated_rejection() -> Dict[str, Any]:
    return {
        "cases_with_repeated_rejections": [],
        "providers_with_repeated_same_reason": [],
        "total_bouncing_cases": 0,
        "data_available": False,
    }


def _empty_false_positive() -> Dict[str, Any]:
    return {
        "total_weak_match_alerts": 0,
        "accepted_after_weak_match": 0,
        "false_positive_rate": None,
        "total_no_weak_match_alert": 0,
        "accepted_without_weak_match_alert": 0,
        "data_available": False,
        "note": "Insufficient data",
    }


def _empty_override_tracking() -> Dict[str, Any]:
    return {
        "total_overrides": 0,
        "by_override_type": [],
        "by_primary_reason": [],
        "override_rate": None,
        "data_available": False,
    }


# ---------------------------------------------------------------------------
# Confidence calibration report
# ---------------------------------------------------------------------------


def build_confidence_calibration_report(organization: Any) -> Dict[str, Any]:
    """Compare predicted confidence level against actual provider outcomes.

    Predicted confidence is proxied from the ``OperationalAlert`` record with
    type ``WEAK_MATCH_NEEDS_REVIEW``.  Cases that ever triggered this alert are
    treated as "predicted low/weak confidence"; all other cases as
    "predicted medium/high confidence".

    For each bucket the report shows:
    - provider acceptance rate
    - placement success rate (PlacementRequest.Status.APPROVED)
    - intake completion rate (IntakeOutcomeStatus.COMPLETED)
    - count of cases in bucket

    Returns
    -------
    dict with ``buckets`` list, counts, and ``data_available`` flag.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_calibration()

    try:
        return _compute_confidence_calibration(organization)
    except Exception:
        logger.exception("build_confidence_calibration_report failed for org %s", getattr(organization, "pk", None))
        return _empty_calibration()


def _compute_confidence_calibration(organization: Any) -> Dict[str, Any]:
    from contracts.models import CaseIntakeProcess, OperationalAlert, PlacementRequest, ProviderEvaluation

    # All cases for this org.
    case_ids = list(
        CaseIntakeProcess.objects.filter(organization=organization).values_list("pk", flat=True)
    )
    if not case_ids:
        return _empty_calibration()

    # Cases that triggered a WEAK_MATCH alert (ever).
    weak_match_case_ids = set(
        OperationalAlert.objects.filter(
            case_id__in=case_ids,
            alert_type=OperationalAlert.AlertType.WEAK_MATCH_NEEDS_REVIEW,
        ).values_list("case_id", flat=True).distinct()
    )

    all_case_id_set = set(case_ids)
    strong_case_ids = all_case_id_set - weak_match_case_ids

    buckets = []
    for label, confidence_label, bucket_case_ids in [
        ("Zwakke match (WEAK_MATCH alert)", "low", weak_match_case_ids),
        ("Sterke/gemiddelde match (geen WEAK_MATCH alert)", "high_medium", strong_case_ids),
    ]:
        if not bucket_case_ids:
            continue

        bucket_list = list(bucket_case_ids)

        # Provider acceptance: at least one ProviderEvaluation.ACCEPT per case.
        accepted_case_ids = set(
            ProviderEvaluation.objects.filter(
                case_id__in=bucket_list,
                decision="accept",
            ).values_list("case_id", flat=True).distinct()
        )

        # Placement success: at least one PlacementRequest with status APPROVED.
        placement_success_ids = set(
            PlacementRequest.objects.filter(
                due_diligence_process_id__in=bucket_list,
                status=PlacementRequest.Status.APPROVED,
            ).values_list("due_diligence_process_id", flat=True).distinct()
        )

        # Intake completion.
        intake_complete_ids = set(
            CaseIntakeProcess.objects.filter(
                pk__in=bucket_list,
                intake_outcome_status=CaseIntakeProcess.IntakeOutcomeStatus.COMPLETED,
            ).values_list("pk", flat=True)
        )

        total = len(bucket_list)
        buckets.append({
            "label": label,
            "confidence_proxy": confidence_label,
            "total_cases": total,
            "provider_acceptance_count": len(accepted_case_ids),
            "provider_acceptance_rate": round(len(accepted_case_ids) / total, 4) if total else None,
            "placement_success_count": len(placement_success_ids),
            "placement_success_rate": round(len(placement_success_ids) / total, 4) if total else None,
            "intake_completion_count": len(intake_complete_ids),
            "intake_completion_rate": round(len(intake_complete_ids) / total, 4) if total else None,
        })

    return {
        "buckets": buckets,
        "total_cases_analysed": len(case_ids),
        "total_weak_match_cases": len(weak_match_case_ids),
        "data_available": bool(buckets),
        "note": (
            "Confidence proxy: WEAK_MATCH_NEEDS_REVIEW alert presence. "
            "Strong/medium = no weak-match alert raised."
        ),
    }


# ---------------------------------------------------------------------------
# Rejection taxonomy report
# ---------------------------------------------------------------------------


def build_rejection_taxonomy_report(organization: Any) -> Dict[str, Any]:
    """Aggregate rejection reason distribution by provider and care category.

    Returns
    -------
    dict with ``by_provider``, ``by_care_category``, and
    ``overall_distribution`` lists.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_taxonomy()

    try:
        return _compute_rejection_taxonomy(organization)
    except Exception:
        logger.exception("build_rejection_taxonomy_report failed for org %s", getattr(organization, "pk", None))
        return _empty_taxonomy()


def _compute_rejection_taxonomy(organization: Any) -> Dict[str, Any]:
    from contracts.models import ProviderEvaluation

    rows = list(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            decision="reject",
        ).select_related("provider", "case__care_category_main").values(
            "reason_code",
            "provider_id",
            "provider__name",
            "case__care_category_main_id",
            "case__care_category_main__name",
        )
    )

    if not rows:
        return _empty_taxonomy()

    # Overall distribution.
    overall_counter: Counter = Counter(r["reason_code"] for r in rows)
    overall_distribution = [
        {"reason_code": code, "count": count, "share": round(count / len(rows), 4)}
        for code, count in overall_counter.most_common()
    ]

    # By provider.
    provider_reason_counts: Dict[Any, Counter] = defaultdict(Counter)
    provider_names: Dict[Any, str] = {}
    for r in rows:
        pid = r["provider_id"]
        provider_reason_counts[pid][r["reason_code"]] += 1
        provider_names[pid] = r["provider__name"] or f"Provider {pid}"

    by_provider = []
    for pid, counter in provider_reason_counts.items():
        total_rejections = sum(counter.values())
        top_reason = counter.most_common(1)[0][0] if counter else None
        by_provider.append({
            "provider_id": pid,
            "provider_name": provider_names.get(pid, f"Provider {pid}"),
            "total_rejections": total_rejections,
            "top_reason_code": top_reason,
            "reason_breakdown": [
                {"reason_code": code, "count": cnt, "share": round(cnt / total_rejections, 4)}
                for code, cnt in counter.most_common()
            ],
        })
    by_provider.sort(key=lambda x: x["total_rejections"], reverse=True)

    # By care category.
    category_reason_counts: Dict[Any, Counter] = defaultdict(Counter)
    category_names: Dict[Any, str] = {}
    for r in rows:
        cid = r["case__care_category_main_id"]
        if cid is None:
            cid = "__unknown__"
        category_reason_counts[cid][r["reason_code"]] += 1
        category_names[cid] = r["case__care_category_main__name"] or "Onbekende categorie"

    by_care_category = []
    for cid, counter in category_reason_counts.items():
        total = sum(counter.values())
        by_care_category.append({
            "care_category_id": cid if cid != "__unknown__" else None,
            "care_category_name": category_names.get(cid, "Onbekende categorie"),
            "total_rejections": total,
            "reason_breakdown": [
                {"reason_code": code, "count": cnt, "share": round(cnt / total, 4)}
                for code, cnt in counter.most_common()
            ],
        })
    by_care_category.sort(key=lambda x: x["total_rejections"], reverse=True)

    return {
        "by_provider": by_provider,
        "by_care_category": by_care_category,
        "overall_distribution": overall_distribution,
        "total_rejections": len(rows),
        "data_available": True,
    }


# ---------------------------------------------------------------------------
# Repeated rejection report
# ---------------------------------------------------------------------------


def build_repeated_rejection_report(organization: Any) -> Dict[str, Any]:
    """Identify cases with repeated rejections and providers with patterns.

    A case is flagged when it has >= 2 rejection evaluations.
    A provider is flagged when it has >= 3 rejections of the same reason code.

    Returns
    -------
    dict with ``cases_with_repeated_rejections``,
    ``providers_with_repeated_same_reason``, and summary counts.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_repeated_rejection()

    try:
        return _compute_repeated_rejections(organization)
    except Exception:
        logger.exception("build_repeated_rejection_report failed for org %s", getattr(organization, "pk", None))
        return _empty_repeated_rejection()


def _compute_repeated_rejections(organization: Any) -> Dict[str, Any]:
    from contracts.models import ProviderEvaluation

    rejection_rows = list(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            decision="reject",
        ).select_related("case").values(
            "case_id",
            "case__title",
            "provider_id",
            "provider__name",
            "reason_code",
            "created_at",
        )
    )

    if not rejection_rows:
        return _empty_repeated_rejection()

    # Bouncing cases: cases with >= 2 rejection records.
    case_rejection_count: Counter = Counter(r["case_id"] for r in rejection_rows)
    case_titles: Dict[Any, str] = {r["case_id"]: r["case__title"] or f"Casus {r['case_id']}" for r in rejection_rows}

    cases_with_repeated = []
    for case_id, count in case_rejection_count.items():
        if count >= 2:
            case_rows = [r for r in rejection_rows if r["case_id"] == case_id]
            providers_involved = list({r["provider_id"] for r in case_rows})
            reason_codes = [r["reason_code"] for r in case_rows]
            cases_with_repeated.append({
                "case_id": case_id,
                "case_title": case_titles.get(case_id, f"Casus {case_id}"),
                "total_rejections": count,
                "providers_involved": len(providers_involved),
                "reason_distribution": dict(Counter(reason_codes).most_common()),
            })
    cases_with_repeated.sort(key=lambda x: x["total_rejections"], reverse=True)

    # Providers with repeated same reason (>= 3 of the same code).
    provider_reason_counter: Dict[tuple, int] = Counter(
        (r["provider_id"], r["reason_code"]) for r in rejection_rows
    )
    provider_names: Dict[Any, str] = {r["provider_id"]: r["provider__name"] or f"Provider {r['provider_id']}" for r in rejection_rows}

    providers_with_pattern = []
    seen_providers: set = set()
    for (pid, reason_code), count in provider_reason_counter.most_common():
        if count >= 3:
            providers_with_pattern.append({
                "provider_id": pid,
                "provider_name": provider_names.get(pid, f"Provider {pid}"),
                "repeated_reason_code": reason_code,
                "repeat_count": count,
            })
            seen_providers.add(pid)

    return {
        "cases_with_repeated_rejections": cases_with_repeated,
        "providers_with_repeated_same_reason": providers_with_pattern,
        "total_bouncing_cases": len(cases_with_repeated),
        "total_providers_with_pattern": len(seen_providers),
        "data_available": bool(cases_with_repeated or providers_with_pattern),
    }


# ---------------------------------------------------------------------------
# Weak-match false positive rate report
# ---------------------------------------------------------------------------


def build_weak_match_false_positive_report(organization: Any) -> Dict[str, Any]:
    """Measure the false positive rate of the WEAK_MATCH_NEEDS_REVIEW alert.

    A false positive is defined as: the WEAK_MATCH alert was raised for a case,
    but the provider eventually accepted (i.e., the alert was needlessly alarming).

    Also reports the true positive rate (alert raised, provider eventually rejected).

    Returns
    -------
    dict with raw counts, false_positive_rate, and true_positive_rate.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_false_positive()

    try:
        return _compute_weak_match_false_positive(organization)
    except Exception:
        logger.exception("build_weak_match_false_positive_report failed for org %s", getattr(organization, "pk", None))
        return _empty_false_positive()


def _compute_weak_match_false_positive(organization: Any) -> Dict[str, Any]:
    from contracts.models import CaseIntakeProcess, OperationalAlert, ProviderEvaluation

    case_ids = list(
        CaseIntakeProcess.objects.filter(organization=organization).values_list("pk", flat=True)
    )
    if not case_ids:
        return _empty_false_positive()

    # Cases that ever had a WEAK_MATCH alert.
    weak_match_case_ids = set(
        OperationalAlert.objects.filter(
            case_id__in=case_ids,
            alert_type=OperationalAlert.AlertType.WEAK_MATCH_NEEDS_REVIEW,
        ).values_list("case_id", flat=True).distinct()
    )

    # Cases without a WEAK_MATCH alert.
    no_weak_match_ids = set(case_ids) - weak_match_case_ids

    # Among WEAK_MATCH cases: how many got accepted?
    accepted_after_weak = set(
        ProviderEvaluation.objects.filter(
            case_id__in=list(weak_match_case_ids),
            decision="accept",
        ).values_list("case_id", flat=True).distinct()
    ) if weak_match_case_ids else set()

    # Among NO-WEAK_MATCH cases: how many got accepted?
    accepted_without_weak = set(
        ProviderEvaluation.objects.filter(
            case_id__in=list(no_weak_match_ids),
            decision="accept",
        ).values_list("case_id", flat=True).distinct()
    ) if no_weak_match_ids else set()

    total_weak = len(weak_match_case_ids)
    total_no_weak = len(no_weak_match_ids)
    accepted_weak = len(accepted_after_weak)
    accepted_no_weak = len(accepted_without_weak)

    false_positive_rate: Optional[float] = None
    true_positive_rate: Optional[float] = None
    if total_weak > 0:
        # FP: alert fired but case was accepted anyway.
        false_positive_rate = round(accepted_weak / total_weak, 4)
        # TP: alert fired and case was NOT accepted (rejected/no response).
        rejected_weak = total_weak - accepted_weak
        true_positive_rate = round(rejected_weak / total_weak, 4)

    # Acceptance rate for non-alerted cases (baseline comparison).
    baseline_acceptance_rate: Optional[float] = None
    if total_no_weak > 0:
        baseline_acceptance_rate = round(accepted_no_weak / total_no_weak, 4)

    return {
        "total_weak_match_alerts": total_weak,
        "accepted_after_weak_match": accepted_weak,
        "rejected_after_weak_match": total_weak - accepted_weak if total_weak else 0,
        "false_positive_rate": false_positive_rate,
        "true_positive_rate": true_positive_rate,
        "total_no_weak_match_alert": total_no_weak,
        "accepted_without_weak_match_alert": accepted_no_weak,
        "baseline_acceptance_rate": baseline_acceptance_rate,
        "data_available": total_weak > 0,
        "note": (
            "False positive: WEAK_MATCH alert fired but provider eventually accepted. "
            "True positive: alert fired and case remained rejected/unaccepted."
        ),
    }


# ---------------------------------------------------------------------------
# Operator override tracking report
# ---------------------------------------------------------------------------


def build_override_tracking_report(organization: Any) -> Dict[str, Any]:
    """Report on operator overrides recorded via DecisionQualityReview.

    Returns
    -------
    dict with total override count, by_override_type, by_primary_reason,
    and the override rate as a fraction of all reviews.
    """
    if not organization or not getattr(organization, "pk", None):
        return _empty_override_tracking()

    try:
        return _compute_override_tracking(organization)
    except Exception:
        logger.exception("build_override_tracking_report failed for org %s", getattr(organization, "pk", None))
        return _empty_override_tracking()


def _compute_override_tracking(organization: Any) -> Dict[str, Any]:
    from contracts.models import DecisionQualityReview

    all_reviews = list(
        DecisionQualityReview.objects.filter(
            case__organization=organization,
        ).values(
            "override_present",
            "override_type",
            "primary_reason",
            "decision_quality",
        )
    )

    if not all_reviews:
        return _empty_override_tracking()

    total_reviews = len(all_reviews)
    overrides = [r for r in all_reviews if r["override_present"]]
    total_overrides = len(overrides)

    by_override_type_counter: Counter = Counter(
        r["override_type"] or "unspecified" for r in overrides
    )
    by_override_type = [
        {"override_type": ot, "count": cnt, "share": round(cnt / total_overrides, 4) if total_overrides else 0}
        for ot, cnt in by_override_type_counter.most_common()
    ]

    by_reason_counter: Counter = Counter(r["primary_reason"] for r in overrides)
    by_primary_reason = [
        {"primary_reason": reason, "count": cnt, "share": round(cnt / total_overrides, 4) if total_overrides else 0}
        for reason, cnt in by_reason_counter.most_common()
    ]

    # Decision quality when override was present.
    override_quality_counter: Counter = Counter(r["decision_quality"] for r in overrides)
    override_quality_distribution = [
        {"decision_quality": dq, "count": cnt}
        for dq, cnt in override_quality_counter.most_common()
    ]

    override_rate = round(total_overrides / total_reviews, 4) if total_reviews else None

    return {
        "total_reviews": total_reviews,
        "total_overrides": total_overrides,
        "by_override_type": by_override_type,
        "by_primary_reason": by_primary_reason,
        "override_quality_distribution": override_quality_distribution,
        "override_rate": override_rate,
        "data_available": total_reviews > 0,
    }


# ---------------------------------------------------------------------------
# Combined report
# ---------------------------------------------------------------------------


def build_full_observability_report(organization: Any) -> Dict[str, Any]:
    """Combine all five observability reports into a single dict.

    Safe when any sub-report fails — each is independently guarded.
    """
    return {
        "confidence_calibration": build_confidence_calibration_report(organization),
        "rejection_taxonomy": build_rejection_taxonomy_report(organization),
        "repeated_rejections": build_repeated_rejection_report(organization),
        "weak_match_false_positive": build_weak_match_false_positive_report(organization),
        "override_tracking": build_override_tracking_report(organization),
    }


# ---------------------------------------------------------------------------
# Extended tuning observability – noisy rules, false-positives, low-confidence
# ---------------------------------------------------------------------------


def build_noisy_rules_report(organization: Any) -> Dict[str, Any]:
    """Identify alert types that fire frequently but are rarely blocking.

    "Noisy" = alert fires for a case but the case progresses to the next
    phase (matching → placement → intake) despite the alert.

    Returns
    -------
    dict with keys:
    ``alert_type_counts``   : list[dict]  — alert_type, total_fired, resolved_without_block, noise_rate
    ``noisiest_alert_type`` : str | None
    ``data_available``      : bool
    """
    try:
        return _compute_noisy_rules(organization)
    except Exception:
        logger.exception("build_noisy_rules_report failed")
        return {"alert_type_counts": [], "noisiest_alert_type": None, "data_available": False}


def _compute_noisy_rules(organization: Any) -> Dict[str, Any]:
    from django.db.models import Count, Q
    from contracts.models import OperationalAlert, CaseIntakeProcess

    # All resolved alerts for the org — resolved means the case moved on.
    alert_rows = list(
        OperationalAlert.objects.filter(
            case__organization=organization,
        ).values("alert_type", "resolved_at")
    )

    if not alert_rows:
        return {"alert_type_counts": [], "noisiest_alert_type": None, "data_available": False}

    total_by_type: Counter = Counter(r["alert_type"] for r in alert_rows)
    resolved_by_type: Counter = Counter(
        r["alert_type"] for r in alert_rows if r["resolved_at"] is not None
    )

    total_all = sum(total_by_type.values())

    alert_type_counts = []
    for alert_type, total_fired in total_by_type.most_common():
        resolved = resolved_by_type.get(alert_type, 0)
        noise_rate = round(resolved / total_fired, 4) if total_fired else 0.0
        alert_type_counts.append({
            "alert_type": alert_type,
            "total_fired": total_fired,
            "resolved_without_block": resolved,
            "noise_rate": noise_rate,
        })

    # Noisiest = highest noise_rate among types with >= 3 fires.
    qualifying = [a for a in alert_type_counts if a["total_fired"] >= 3]
    noisiest = max(qualifying, key=lambda a: a["noise_rate"])["alert_type"] if qualifying else None

    return {
        "alert_type_counts": alert_type_counts,
        "noisiest_alert_type": noisiest,
        "total_alerts_analysed": total_all,
        "data_available": True,
    }


def build_false_positive_signals_report(organization: Any) -> Dict[str, Any]:
    """Identify alert types that fired but the provider later accepted the case.

    A false positive is: an alert was raised for a case, but the case later
    received at least one provider ACCEPT evaluation.

    Returns
    -------
    dict with keys:
    ``by_alert_type``  : list[dict]  — alert_type, fp_count, total_fired, fp_rate
    ``top_fp_type``    : str | None  — alert type with highest false-positive rate
    ``data_available`` : bool
    """
    try:
        return _compute_false_positive_signals(organization)
    except Exception:
        logger.exception("build_false_positive_signals_report failed")
        return {"by_alert_type": [], "top_fp_type": None, "data_available": False}


def _compute_false_positive_signals(organization: Any) -> Dict[str, Any]:
    from django.db.models import Q
    from contracts.models import OperationalAlert, ProviderEvaluation

    # Cases that eventually got an ACCEPT evaluation.
    accepted_case_ids = set(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            decision="accept",
        ).values_list("case_id", flat=True)
    )

    if not accepted_case_ids:
        return {"by_alert_type": [], "top_fp_type": None, "data_available": False}

    alert_rows = list(
        OperationalAlert.objects.filter(
            case__organization=organization,
        ).values("alert_type", "case_id")
    )

    if not alert_rows:
        return {"by_alert_type": [], "top_fp_type": None, "data_available": False}

    total_by_type: Counter = Counter(r["alert_type"] for r in alert_rows)
    fp_by_type: Counter = Counter(
        r["alert_type"] for r in alert_rows if r["case_id"] in accepted_case_ids
    )

    by_alert_type = []
    for alert_type, total_fired in total_by_type.most_common():
        fp_count = fp_by_type.get(alert_type, 0)
        fp_rate = round(fp_count / total_fired, 4) if total_fired else 0.0
        by_alert_type.append({
            "alert_type": alert_type,
            "total_fired": total_fired,
            "fp_count": fp_count,
            "fp_rate": fp_rate,
        })

    qualifying = [a for a in by_alert_type if a["total_fired"] >= 3]
    top_fp = max(qualifying, key=lambda a: a["fp_rate"])["alert_type"] if qualifying else None

    return {
        "by_alert_type": by_alert_type,
        "top_fp_type": top_fp,
        "total_cases_with_accept": len(accepted_case_ids),
        "data_available": True,
    }


def build_low_confidence_accepted_report(organization: Any) -> Dict[str, Any]:
    """Identify cases where a WEAK_MATCH alert fired but provider accepted.

    These cases indicate that the weak-match confidence threshold may be too
    conservative — the provider accepted despite a low-confidence signal.

    Returns
    -------
    dict with keys:
    ``count``              : int  — cases with WEAK_MATCH alert + accept
    ``total_weak_match``   : int  — total cases with any WEAK_MATCH alert
    ``false_positive_rate``: float | None
    ``cases``              : list[dict]  — case_id, case_title (up to 20)
    ``data_available``     : bool
    """
    try:
        return _compute_low_confidence_accepted(organization)
    except Exception:
        logger.exception("build_low_confidence_accepted_report failed")
        return {"count": 0, "total_weak_match": 0, "false_positive_rate": None, "cases": [], "data_available": False}


def _compute_low_confidence_accepted(organization: Any) -> Dict[str, Any]:
    from contracts.models import OperationalAlert, ProviderEvaluation

    weak_match_type = "weak_match_needs_review"

    # Cases that had a WEAK_MATCH alert.
    weak_match_case_ids = set(
        OperationalAlert.objects.filter(
            case__organization=organization,
            alert_type=weak_match_type,
        ).values_list("case_id", flat=True)
    )

    total_weak_match = len(weak_match_case_ids)
    if total_weak_match == 0:
        return {"count": 0, "total_weak_match": 0, "false_positive_rate": None, "cases": [], "data_available": False}

    # Among those, which also got an ACCEPT evaluation?
    accepted_rows = list(
        ProviderEvaluation.objects.filter(
            case__organization=organization,
            case_id__in=weak_match_case_ids,
            decision="accept",
        ).values("case_id", "case__title").distinct()
    )

    count = len(accepted_rows)
    false_positive_rate = round(count / total_weak_match, 4) if total_weak_match else None

    cases = [
        {
            "case_id": r["case_id"],
            "case_title": r["case__title"] or f"Casus {r['case_id']}",
        }
        for r in accepted_rows[:20]
    ]

    return {
        "count": count,
        "total_weak_match": total_weak_match,
        "false_positive_rate": false_positive_rate,
        "cases": cases,
        "data_available": True,
    }


def build_top_overridden_rules_report(organization: Any) -> Dict[str, Any]:
    """Identify alert types most correlated with operator overrides.

    Uses the DecisionQualityReview records to find override events, then
    correlates them with the most recent unresolved alert on the same case.

    Returns
    -------
    dict with keys:
    ``by_alert_type``   : list[dict]  — alert_type, case_count, override_count
    ``top_overridden``  : str | None
    ``data_available``  : bool
    """
    try:
        return _compute_top_overridden_rules(organization)
    except Exception:
        logger.exception("build_top_overridden_rules_report failed")
        return {"by_alert_type": [], "top_overridden": None, "data_available": False}


def _compute_top_overridden_rules(organization: Any) -> Dict[str, Any]:
    from contracts.models import DecisionQualityReview, OperationalAlert

    # Overrides: all DecisionQualityReview rows with override_present=True.
    override_rows = list(
        DecisionQualityReview.objects.filter(
            case__organization=organization,
            override_present=True,
        ).values("case_id")
    )

    if not override_rows:
        return {"by_alert_type": [], "top_overridden": None, "data_available": False}

    override_case_ids = {r["case_id"] for r in override_rows}

    # For each case with an override, find which alert types were active.
    alert_rows = list(
        OperationalAlert.objects.filter(
            case__organization=organization,
            case_id__in=override_case_ids,
        ).values("case_id", "alert_type")
    )

    if not alert_rows:
        return {"by_alert_type": [], "top_overridden": None, "data_available": False}

    # Group by alert_type: count distinct cases that had an override.
    by_type: Dict[str, set] = defaultdict(set)
    for r in alert_rows:
        by_type[r["alert_type"]].add(r["case_id"])

    override_count_by_type = {
        at: len(case_ids) for at, case_ids in by_type.items()
    }

    by_alert_type = sorted(
        [
            {
                "alert_type": alert_type,
                "override_case_count": count,
            }
            for alert_type, count in override_count_by_type.items()
        ],
        key=lambda x: -x["override_case_count"],
    )

    top_overridden = by_alert_type[0]["alert_type"] if by_alert_type else None

    return {
        "by_alert_type": by_alert_type,
        "top_overridden": top_overridden,
        "total_overridden_cases": len(override_case_ids),
        "data_available": True,
    }


def build_tuning_observability_report(organization: Any) -> Dict[str, Any]:
    """Combine all four tuning-specific observability sub-reports.

    Intended for the tuning admin view alongside ``build_full_observability_report``.
    """
    return {
        "noisy_rules": build_noisy_rules_report(organization),
        "false_positive_signals": build_false_positive_signals_report(organization),
        "low_confidence_accepted": build_low_confidence_accepted_report(organization),
        "top_overridden_rules": build_top_overridden_rules_report(organization),
    }


def build_info_request_metrics_report(organization: Any) -> Dict[str, Any]:
    """Compute observability metrics for the provider information request loop.

    Metrics
    -------
    - total_open: open or in_progress requests for the org
    - total_resolved: resolved or resubmitted requests for the org
    - average_resolution_hours: average hours between created_at and resolved_at
    - stale_count: requests open for more than STALE_DAYS days
    - repeated_request_cases: cases with ≥2 information requests (repeat loop)
    - providers_with_most_requests: top providers by total info-request count
    - data_available: False when there are no requests at all
    """
    try:
        from django.db.models import Avg, Count, ExpressionWrapper, F, FloatField
        from django.utils import timezone
        from contracts.models import CaseInformationRequest

        _STALE_DAYS = 3
        cutoff = timezone.now() - __import__('datetime').timedelta(days=_STALE_DAYS)

        base_qs = CaseInformationRequest.objects.filter(case__organization=organization)
        total = base_qs.count()
        if not total:
            return {
                "total_open": 0,
                "total_resolved": 0,
                "average_resolution_hours": None,
                "stale_count": 0,
                "repeated_request_cases": [],
                "providers_with_most_requests": [],
                "data_available": False,
            }

        open_statuses = [CaseInformationRequest.Status.OPEN, CaseInformationRequest.Status.IN_PROGRESS]
        closed_statuses = [CaseInformationRequest.Status.RESOLVED, CaseInformationRequest.Status.RESUBMITTED]

        total_open = base_qs.filter(status__in=open_statuses).count()
        total_resolved = base_qs.filter(status__in=closed_statuses).count()
        stale_count = base_qs.filter(status__in=open_statuses, created_at__lt=cutoff).count()

        # Average resolution time (only for requests that have a resolved_at)
        resolved_qs = base_qs.filter(resolved_at__isnull=False)
        avg_resolution_hours: Optional[float] = None
        if resolved_qs.exists():
            # Compute in Python to avoid DB-level interval arithmetic portability issues
            durations = []
            for req in resolved_qs.only('created_at', 'resolved_at'):
                diff = req.resolved_at - req.created_at
                durations.append(diff.total_seconds() / 3600.0)
            avg_resolution_hours = round(sum(durations) / len(durations), 1) if durations else None

        # Cases with repeated requests (≥2 info requests)
        repeated_cases_qs = (
            base_qs.values('case')
            .annotate(request_count=Count('id'))
            .filter(request_count__gte=2)
            .order_by('-request_count')[:20]
        )
        repeated_request_cases = [
            {"case_id": row["case"], "request_count": row["request_count"]}
            for row in repeated_cases_qs
        ]

        # Providers with most info requests
        providers_qs = (
            base_qs.values('provider', 'provider__name')
            .annotate(total_requests=Count('id'))
            .order_by('-total_requests')[:10]
        )
        providers_with_most_requests = [
            {
                "provider_id": row["provider"],
                "provider_name": row["provider__name"],
                "total_requests": row["total_requests"],
            }
            for row in providers_qs
        ]

        return {
            "total_open": total_open,
            "total_resolved": total_resolved,
            "average_resolution_hours": avg_resolution_hours,
            "stale_count": stale_count,
            "repeated_request_cases": repeated_request_cases,
            "providers_with_most_requests": providers_with_most_requests,
            "data_available": True,
        }
    except Exception:
        logger.exception("build_info_request_metrics_report failed")
        return {
            "total_open": 0,
            "total_resolved": 0,
            "average_resolution_hours": None,
            "stale_count": 0,
            "repeated_request_cases": [],
            "providers_with_most_requests": [],
            "data_available": False,
        }
